#!/usr/bin/env python3

import sys
import enum
import math
import pytiled_parser

import characters

from util import *
from pathlib import Path
from pytiled_parser.tiled_object import TiledObject

texts = (
    "X0001_MID_SCENARIO_MAP_BEGIN",
    "X0001_MID_SCENARIO_MAP_END",
    "X0001_MID_SCENARIO_OPENING",
    "X0002_MID_SCENARIO_MAP_BEGIN",
    "X0002_MID_SCENARIO_MAP_END",
    "X0003_MID_SCENARIO_MAP_BEGIN",
    "X0003_MID_SCENARIO_MAP_END",
    "X0004_MID_SCENARIO_MAP_BEGIN",
    "X0004_MID_SCENARIO_MAP_END",
    "X0005_MID_SCENARIO_MAP_BEGIN",
    "X0005_MID_SCENARIO_MAP_END",
    "X0006_MID_SCENARIO_MAP_BEGIN",
    "X0006_MID_SCENARIO_MAP_END",
    "X0021_MID_SCENARIO_MAP_BEGIN",
    "X0021_MID_SCENARIO_MAP_END",
    "X0021_MID_SCENARIO_OPENING",
    "X0022_MID_SCENARIO_MAP_BEGIN",
    "X0022_MID_SCENARIO_MAP_END",
    "X0023_MID_SCENARIO_ENDING",
    "X0023_MID_SCENARIO_MAP_BEGIN",
    "X0023_MID_SCENARIO_MAP_END",
    "X0031_MID_SCENARIO_MAP_BEGIN",
    "X0031_MID_SCENARIO_MAP_END",
    "X0031_MID_SCENARIO_OPENING",
    "X0032_MID_SCENARIO_MAP_BEGIN",
    "X0032_MID_SCENARIO_MAP_END",
    "X0033_MID_SCENARIO_MAP_BEGIN",
    "X0033_MID_SCENARIO_MAP_END",
    "X0041_MID_SCENARIO_MAP_BEGIN",
    "X0041_MID_SCENARIO_MAP_END",
    "X0041_MID_SCENARIO_OPENING",
    "X0042_MID_SCENARIO_MAP_BEGIN",
    "X0042_MID_SCENARIO_MAP_END",
    "X0043_MID_SCENARIO_ENDING",
    "X0043_MID_SCENARIO_MAP_BEGIN",
    "X0043_MID_SCENARIO_MAP_END",
    "X0051_MID_SCENARIO_MAP_BEGIN",
    "X0051_MID_SCENARIO_MAP_END",
    "X0051_MID_SCENARIO_OPENING",
    "X0052_MID_SCENARIO_MAP_BEGIN",
    "X0052_MID_SCENARIO_MAP_END",
    "X0053_MID_SCENARIO_MAP_BEGIN",
    "X0053_MID_SCENARIO_MAP_END",
    "X0061_MID_SCENARIO_MAP_BEGIN",
    "X0061_MID_SCENARIO_MAP_END",
    "X0061_MID_SCENARIO_OPENING",
    "X0062_MID_SCENARIO_MAP_BEGIN",
    "X0062_MID_SCENARIO_MAP_END",
    "X0063_MID_SCENARIO_ENDING",
    "X0063_MID_SCENARIO_MAP_BEGIN",
    "X0063_MID_SCENARIO_MAP_END",
    "X0071_MID_SCENARIO_MAP_BEGIN",
    "X0071_MID_SCENARIO_MAP_END",
    "X0071_MID_SCENARIO_OPENING",
    "X0072_MID_SCENARIO_MAP_BEGIN",
    "X0072_MID_SCENARIO_MAP_END",
    "X0073_MID_SCENARIO_MAP_BEGIN",
    "X0073_MID_SCENARIO_MAP_END",
    "X0081_MID_SCENARIO_MAP_BEGIN",
    "X0081_MID_SCENARIO_MAP_END",
    "X0081_MID_SCENARIO_OPENING",
    "X0082_MID_SCENARIO_MAP_BEGIN",
    "X0082_MID_SCENARIO_MAP_END",
    "X0083_MID_SCENARIO_MAP_BEGIN",
    "X0083_MID_SCENARIO_MAP_END",
    "X0091_MID_SCENARIO_MAP_BEGIN",
    "X0091_MID_SCENARIO_MAP_END",
    "X0092_MID_SCENARIO_MAP_BEGIN",
    "X0092_MID_SCENARIO_MAP_END",
    "X0093_MID_SCENARIO_ENDING",
    "X0093_MID_SCENARIO_MAP_BEGIN",
    "X0093_MID_SCENARIO_MAP_END",
    "X0101_MID_SCENARIO_MAP_BEGIN",
    "X0101_MID_SCENARIO_MAP_END",
    "X0101_MID_SCENARIO_OPENING",
    "X0102_MID_SCENARIO_MAP_BEGIN",
    "X0102_MID_SCENARIO_MAP_END",
    "X0103_MID_SCENARIO_MAP_BEGIN",
    "X0103_MID_SCENARIO_MAP_END",
    "X0111_MID_SCENARIO_MAP_BEGIN",
    "X0111_MID_SCENARIO_MAP_END",
    "X0111_MID_SCENARIO_OPENING",
    "X0112_MID_SCENARIO_MAP_BEGIN",
    "X0112_MID_SCENARIO_MAP_END",
    "X0113_MID_SCENARIO_MAP_BEGIN",
    "X0113_MID_SCENARIO_MAP_END",
    "X0121_MID_SCENARIO_MAP_BEGIN",
    "X0121_MID_SCENARIO_MAP_END",
    "X0122_MID_SCENARIO_MAP_BEGIN",
    "X0122_MID_SCENARIO_MAP_END",
    "X0123_MID_SCENARIO_ENDING",
    "X0123_MID_SCENARIO_MAP_BEGIN",
    "X0123_MID_SCENARIO_MAP_END",
    "X0131_MID_SCENARIO_MAP_BEGIN",
    "X0131_MID_SCENARIO_MAP_END",
    "X0132_MID_SCENARIO_MAP_BEGIN",
    "X0132_MID_SCENARIO_MAP_END",
    "X0133_MID_SCENARIO_MAP_BEGIN",
    "X0133_MID_SCENARIO_MAP_END",
    "X0141_MID_SCENARIO_MAP_BEGIN",
    "X0141_MID_SCENARIO_MAP_END",
    "X0141_MID_SCENARIO_OPENING",
    "X0142_MID_SCENARIO_MAP_BEGIN",
    "X0142_MID_SCENARIO_MAP_END",
    "X0143_MID_SCENARIO_MAP_BEGIN",
    "X0143_MID_SCENARIO_MAP_END",
    "X0151_MID_SCENARIO_MAP_BEGIN",
    "X0151_MID_SCENARIO_MAP_END",
    "X0151_MID_SCENARIO_OPENING",
    "X0152_MID_SCENARIO_MAP_BEGIN",
    "X0152_MID_SCENARIO_MAP_END",
    "X0153_MID_SCENARIO_MAP_BEGIN",
    "X0153_MID_SCENARIO_MAP_END",
    "X0161_MID_SCENARIO_MAP_BEGIN",
    "X0161_MID_SCENARIO_MAP_END",
    "X0161_MID_SCENARIO_OPENING",
    "X0162_MID_SCENARIO_MAP_BEGIN",
    "X0162_MID_SCENARIO_MAP_END",
    "X0163_MID_SCENARIO_MAP_BEGIN",
    "X0163_MID_SCENARIO_MAP_END",
    "X0171_MID_SCENARIO_MAP_BEGIN",
    "X0171_MID_SCENARIO_MAP_END",
    "X0171_MID_SCENARIO_OPENING",
    "X0172_MID_SCENARIO_MAP_BEGIN",
    "X0172_MID_SCENARIO_MAP_END",
    "X0173_MID_SCENARIO_MAP_BEGIN",
    "X0173_MID_SCENARIO_MAP_END",
    "X0181_MID_SCENARIO_MAP_BEGIN",
    "X0181_MID_SCENARIO_MAP_END",
    "X0181_MID_SCENARIO_OPENING",
    "X0182_MID_SCENARIO_MAP_BEGIN",
    "X0182_MID_SCENARIO_MAP_END",
    "X0183_MID_SCENARIO_MAP_BEGIN",
    "X0183_MID_SCENARIO_MAP_END",
    "X0191_MID_SCENARIO_MAP_BEGIN",
    "X0191_MID_SCENARIO_MAP_END",
    "X0191_MID_SCENARIO_OPENING",
    "X0192_MID_SCENARIO_MAP_BEGIN",
    "X0192_MID_SCENARIO_MAP_END",
    "X0193_MID_SCENARIO_MAP_BEGIN",
    "X0193_MID_SCENARIO_MAP_END",
    "X0201_MID_SCENARIO_MAP_BEGIN",
    "X0201_MID_SCENARIO_MAP_END",
    "X0201_MID_SCENARIO_OPENING",
    "X0202_MID_SCENARIO_MAP_BEGIN",
    "X0202_MID_SCENARIO_MAP_END",
    "X0203_MID_SCENARIO_ENDING",
    "X0203_MID_SCENARIO_MAP_BEGIN",
    "X0203_MID_SCENARIO_MAP_END",
    "X0211_MID_SCENARIO_MAP_BEGIN",
    "X0211_MID_SCENARIO_MAP_END",
    "X0211_MID_SCENARIO_OPENING",
    "X0212_MID_SCENARIO_MAP_BEGIN",
    "X0212_MID_SCENARIO_MAP_END",
    "X0213_MID_SCENARIO_ENDING",
    "X0213_MID_SCENARIO_MAP_BEGIN",
    "X0213_MID_SCENARIO_MAP_END",
    "X0221_MID_SCENARIO_MAP_BEGIN",
    "X0221_MID_SCENARIO_MAP_END",
    "X0221_MID_SCENARIO_OPENING",
    "X0222_MID_SCENARIO_MAP_BEGIN",
    "X0222_MID_SCENARIO_MAP_END",
    "X0223_MID_SCENARIO_MAP_BEGIN",
    "X0223_MID_SCENARIO_MAP_END",
    "X0231_MID_SCENARIO_MAP_BEGIN",
    "X0231_MID_SCENARIO_MAP_END",
    "X0231_MID_SCENARIO_OPENING",
    "X0232_MID_SCENARIO_MAP_BEGIN",
    "X0232_MID_SCENARIO_MAP_END",
    "X0233_MID_SCENARIO_MAP_BEGIN",
    "X0233_MID_SCENARIO_MAP_END",
    "X0241_MID_SCENARIO_MAP_BEGIN",
    "X0241_MID_SCENARIO_MAP_END",
    "X0241_MID_SCENARIO_OPENING",
    "X0242_MID_SCENARIO_MAP_BEGIN",
    "X0242_MID_SCENARIO_MAP_END",
    "X0243_MID_SCENARIO_MAP_BEGIN",
    "X0243_MID_SCENARIO_MAP_END",
    "X0251_MID_SCENARIO_MAP_BEGIN",
    "X0251_MID_SCENARIO_MAP_END",
    "X0251_MID_SCENARIO_OPENING",
    "X0252_MID_SCENARIO_MAP_BEGIN",
    "X0252_MID_SCENARIO_MAP_END",
    "X0253_MID_SCENARIO_MAP_BEGIN",
    "X0253_MID_SCENARIO_MAP_END",
    "X0261_MID_SCENARIO_MAP_BEGIN",
    "X0261_MID_SCENARIO_MAP_END",
    "X0261_MID_SCENARIO_OPENING",
    "X0262_MID_SCENARIO_MAP_BEGIN",
    "X0262_MID_SCENARIO_MAP_END",
    "X0262_MID_SCENARIO_OPENING",
    "X0263_MID_SCENARIO_ENDING",
    "X0263_MID_SCENARIO_MAP_BEGIN",
    "X0263_MID_SCENARIO_MAP_END",
    "X0263_MID_SCENARIO_OPENING",
    "X0271_MID_SCENARIO_MAP_BEGIN",
    "X0271_MID_SCENARIO_MAP_END",
    "X0271_MID_SCENARIO_OPENING",
    "X0272_MID_SCENARIO_MAP_BEGIN",
    "X0272_MID_SCENARIO_MAP_END",
    "X0273_MID_SCENARIO_MAP_BEGIN",
    "X0273_MID_SCENARIO_MAP_END",
    "X0281_MID_SCENARIO_MAP_BEGIN",
    "X0281_MID_SCENARIO_MAP_END",
    "X0281_MID_SCENARIO_OPENING",
    "X0282_MID_SCENARIO_MAP_BEGIN",
    "X0282_MID_SCENARIO_MAP_END",
    "X0283_MID_SCENARIO_MAP_BEGIN",
    "X0283_MID_SCENARIO_MAP_END",
    "X0291_MID_SCENARIO_MAP_BEGIN",
    "X0291_MID_SCENARIO_MAP_END",
    "X0291_MID_SCENARIO_OPENING",
    "X0292_MID_SCENARIO_MAP_BEGIN",
    "X0292_MID_SCENARIO_MAP_END",
    "X0293_MID_SCENARIO_MAP_BEGIN",
    "X0293_MID_SCENARIO_MAP_END",
    "X0301_MID_SCENARIO_MAP_BEGIN",
    "X0301_MID_SCENARIO_MAP_END",
    "X0301_MID_SCENARIO_OPENING",
    "X0302_MID_SCENARIO_MAP_BEGIN",
    "X0302_MID_SCENARIO_MAP_END",
    "X0303_MID_SCENARIO_MAP_BEGIN",
    "X0303_MID_SCENARIO_MAP_END",
    "X0311_MID_SCENARIO_MAP_BEGIN",
    "X0311_MID_SCENARIO_MAP_END",
    "X0311_MID_SCENARIO_OPENING",
    "X0312_MID_SCENARIO_MAP_BEGIN",
    "X0312_MID_SCENARIO_MAP_END",
    "X0313_MID_SCENARIO_MAP_BEGIN",
    "X0313_MID_SCENARIO_MAP_END",
    "X0321_MID_SCENARIO_MAP_BEGIN",
    "X0321_MID_SCENARIO_MAP_END",
    "X0321_MID_SCENARIO_OPENING",
    "X0322_MID_SCENARIO_MAP_BEGIN",
    "X0322_MID_SCENARIO_MAP_END",
    "X0323_MID_SCENARIO_MAP_BEGIN",
    "X0323_MID_SCENARIO_MAP_END",
    "X0331_MID_SCENARIO_MAP_BEGIN",
    "X0331_MID_SCENARIO_MAP_END",
    "X0331_MID_SCENARIO_OPENING",
    "X0332_MID_SCENARIO_MAP_BEGIN",
    "X0332_MID_SCENARIO_MAP_END",
    "X0333_MID_SCENARIO_MAP_BEGIN",
    "X0333_MID_SCENARIO_MAP_END",
    "X0341_MID_SCENARIO_MAP_BEGIN",
    "X0341_MID_SCENARIO_MAP_END",
    "X0341_MID_SCENARIO_OPENING",
    "X0342_MID_SCENARIO_MAP_BEGIN",
    "X0342_MID_SCENARIO_MAP_END",
    "X0343_MID_SCENARIO_MAP_BEGIN",
    "X0343_MID_SCENARIO_MAP_END",
    "X0351_MID_SCENARIO_MAP_BEGIN",
    "X0351_MID_SCENARIO_MAP_END",
    "X0351_MID_SCENARIO_OPENING",
    "X0352_MID_SCENARIO_MAP_BEGIN",
    "X0352_MID_SCENARIO_MAP_END",
    "X0353_MID_SCENARIO_MAP_BEGIN",
    "X0353_MID_SCENARIO_MAP_END",
    "X0361_MID_SCENARIO_MAP_BEGIN",
    "X0361_MID_SCENARIO_MAP_END",
    "X0361_MID_SCENARIO_OPENING",
    "X0362_MID_SCENARIO_MAP_BEGIN",
    "X0362_MID_SCENARIO_MAP_END",
    "X0363_MID_SCENARIO_MAP_BEGIN",
    "X0363_MID_SCENARIO_MAP_END",
    "X0371_MID_SCENARIO_MAP_BEGIN",
    "X0371_MID_SCENARIO_MAP_END",
    "X0371_MID_SCENARIO_OPENING",
    "X0372_MID_SCENARIO_MAP_BEGIN",
    "X0372_MID_SCENARIO_MAP_END",
    "X0373_MID_SCENARIO_MAP_BEGIN",
    "X0373_MID_SCENARIO_MAP_END",
    "X0381_MID_SCENARIO_MAP_BEGIN",
    "X0381_MID_SCENARIO_MAP_END",
    "X0381_MID_SCENARIO_OPENING",
    "X0382_MID_SCENARIO_MAP_BEGIN",
    "X0382_MID_SCENARIO_MAP_END",
    "X0383_MID_SCENARIO_MAP_BEGIN",
    "X0383_MID_SCENARIO_MAP_END",
    "X0391_MID_SCENARIO_MAP_BEGIN",
    "X0391_MID_SCENARIO_MAP_END",
    "X0391_MID_SCENARIO_OPENING",
    "X0392_MID_SCENARIO_MAP_BEGIN",
    "X0392_MID_SCENARIO_MAP_END",
    "X0393_MID_SCENARIO_MAP_BEGIN",
    "X0393_MID_SCENARIO_MAP_END",
    "X0401_MID_SCENARIO_MAP_BEGIN",
    "X0401_MID_SCENARIO_MAP_END",
    "X0401_MID_SCENARIO_OPENING",
    "X0402_MID_SCENARIO_MAP_BEGIN",
    "X0402_MID_SCENARIO_MAP_END",
    "X0403_MID_SCENARIO_MAP_BEGIN",
    "X0403_MID_SCENARIO_MAP_END",
    "X0411_MID_SCENARIO_MAP_BEGIN",
    "X0411_MID_SCENARIO_MAP_END",
    "X0411_MID_SCENARIO_OPENING",
    "X0412_MID_SCENARIO_MAP_BEGIN",
    "X0412_MID_SCENARIO_MAP_END",
    "X0413_MID_SCENARIO_MAP_BEGIN",
    "X0413_MID_SCENARIO_MAP_END",
    "X0421_MID_SCENARIO_MAP_BEGIN",
    "X0421_MID_SCENARIO_MAP_END",
    "X0421_MID_SCENARIO_OPENING",
    "X0422_MID_SCENARIO_MAP_BEGIN",
    "X0422_MID_SCENARIO_MAP_END",
    "X0423_MID_SCENARIO_MAP_BEGIN",
    "X0423_MID_SCENARIO_MAP_END",
    "X0431_MID_SCENARIO_MAP_BEGIN",
    "X0431_MID_SCENARIO_MAP_END",
    "X0431_MID_SCENARIO_OPENING",
    "X0432_MID_SCENARIO_MAP_BEGIN",
    "X0432_MID_SCENARIO_MAP_END",
    "X0433_MID_SCENARIO_MAP_BEGIN",
    "X0433_MID_SCENARIO_MAP_END",
    "X0441_MID_SCENARIO_ENDING",
    "X0441_MID_SCENARIO_MAP_BEGIN",
    "X0441_MID_SCENARIO_MAP_END",
    "X0441_MID_SCENARIO_OPENING",
    "X0442_MID_SCENARIO_MAP_BEGIN",
    "X0442_MID_SCENARIO_MAP_END",
    "X0443_MID_SCENARIO_MAP_BEGIN",
    "X0443_MID_SCENARIO_MAP_END",
    "X0451_MID_SCENARIO_MAP_BEGIN",
    "X0451_MID_SCENARIO_MAP_END",
    "X0451_MID_SCENARIO_OPENING",
    "X0452_MID_SCENARIO_MAP_BEGIN",
    "X0452_MID_SCENARIO_MAP_END",
    "X0453_MID_SCENARIO_MAP_BEGIN",
    "X0453_MID_SCENARIO_MAP_END",
    "X0461_MID_SCENARIO_MAP_BEGIN",
    "X0461_MID_SCENARIO_MAP_END",
    "X0461_MID_SCENARIO_OPENING",
    "X0462_MID_SCENARIO_MAP_BEGIN",
    "X0462_MID_SCENARIO_MAP_END",
    "X0463_MID_SCENARIO_MAP_BEGIN",
    "X0463_MID_SCENARIO_MAP_END",
    "X0471_MID_SCENARIO_MAP_BEGIN",
    "X0471_MID_SCENARIO_MAP_END",
    "X0471_MID_SCENARIO_OPENING",
    "X0472_MID_SCENARIO_MAP_BEGIN",
    "X0472_MID_SCENARIO_MAP_END",
    "X0473_MID_SCENARIO_MAP_BEGIN",
    "X0473_MID_SCENARIO_MAP_END",
    "X0481_MID_SCENARIO_MAP_BEGIN",
    "X0481_MID_SCENARIO_MAP_END",
    "X0481_MID_SCENARIO_OPENING",
    "X0482_MID_SCENARIO_MAP_BEGIN",
    "X0482_MID_SCENARIO_MAP_END",
    "X0483_MID_SCENARIO_MAP_BEGIN",
    "X0483_MID_SCENARIO_MAP_END",
    "X0491_MID_SCENARIO_MAP_BEGIN",
    "X0491_MID_SCENARIO_MAP_END",
    "X0491_MID_SCENARIO_OPENING",
    "X0492_MID_SCENARIO_MAP_BEGIN",
    "X0492_MID_SCENARIO_MAP_END",
    "X0493_MID_SCENARIO_MAP_BEGIN",
    "X0493_MID_SCENARIO_MAP_END",
    "XX001_MID_SCENARIO_ENDING",
    "XX001_MID_SCENARIO_MAP_BEGIN",
    "XX001_MID_SCENARIO_MAP_END",
    "XX002_MID_SCENARIO_ENDING",
    "XX002_MID_SCENARIO_MAP_BEGIN",
    "XX002_MID_SCENARIO_MAP_END",
    "XX002_MID_SCENARIO_OPENING",
    "XX003_MID_SCENARIO_MAP_BEGIN",
    "XX003_MID_SCENARIO_MAP_END",
    "XX003_MID_SCENARIO_OPENING",
    "XX004_MID_SCENARIO_MAP_BEGIN",
    "XX004_MID_SCENARIO_MAP_END",
    "XX004_MID_SCENARIO_OPENING",
    "XX005_MID_SCENARIO_ENDING",
    "XX005_MID_SCENARIO_MAP_BEGIN",
    "XX005_MID_SCENARIO_MAP_END",
    "XX005_MID_SCENARIO_OPENING",
)

bgms = {
	"X0001_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0001_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0002_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0003_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0004_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0005_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0006_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0021_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_SERIOUS_01",
	"X0022_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0023_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0031_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0031_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0032_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0033_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0041_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_02",
	"X0041_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0042_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_01",
	"X0043_MID_SCENARIO_ENDING_BGM": "BGM_EVENT_SERIOUS_01",
	"X0043_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0051_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0051_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0052_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0053_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0061_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0062_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0063_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0071_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0071_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0072_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0073_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0081_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0081_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0082_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0083_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0091_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_02",
	"X0092_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0093_MID_SCENARIO_ENDING_BGM": "BGM_EVENT_SERIOUS_04",
	"X0093_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_02",
	"X0101_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0102_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0103_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0111_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0111_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0112_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0113_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0121_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_02",
	"X0122_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_04",
	"X0123_MID_SCENARIO_ENDING_BGM": "BGM_EVENT_SERIOUS_01",
	"X0123_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0131_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0132_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0133_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0141_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0142_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0143_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0151_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0151_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0152_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_01",
	"X0153_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0161_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_05",
	"X0161_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0162_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_05",
	"X0163_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_05",
	"X0171_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0171_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0172_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0173_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0181_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0181_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0182_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0183_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0191_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0191_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0192_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0193_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0201_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0201_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0202_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0203_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0211_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0211_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0212_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0213_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0221_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0222_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03",
	"X0223_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_04",
	"X0231_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_02",
	"X0231_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0232_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0233_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0241_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0241_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0242_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0243_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0251_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_04",
	"X0251_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0252_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0253_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0261_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_AMB_USERNAME",
	"X0261_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_SERIOUS_04",
	"X0262_MID_SCENARIO_OPENING_BGM": "BGM_AMB_USERNAME",
	"X0263_MID_SCENARIO_ENDING_BGM": "BGM_EVENT_SERIOUS_04",
	"X0263_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_SERIOUS_01",
	"X0271_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0271_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0272_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_02",
	"X0273_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0281_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_05",
	"X0281_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0282_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_05",
	"X0283_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_05",
	"X0291_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0291_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0292_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0293_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0301_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0301_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0302_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0303_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0311_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0311_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_SERIOUS_02",
	"X0312_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0313_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0321_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0321_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_02",
	"X0322_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0323_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0331_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0331_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0332_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0333_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0341_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0341_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0342_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0343_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0351_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0351_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0352_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0353_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0361_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0362_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0363_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0371_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0371_MID_SCENARIO_OPENING_BGM": "BGM_MENU_TITLE",
	"X0372_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0373_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0381_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0381_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0382_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0383_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0391_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0391_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0392_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_03",
	"X0393_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0401_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_14",
	"X0401_MID_SCENARIO_OPENING_BGM": "BGM_MAP_FE14_05",
	"X0402_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FE14_14",
	"X0403_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0411_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"X0412_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_01",
	"X0413_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0421_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0421_MID_SCENARIO_OPENING_BGM": "BGM_MNS_FE15_01",
	"X0422_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0423_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0431_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0431_MID_SCENARIO_OPENING_BGM": "BGM_MNS_FE07_03",
	"X0432_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0433_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0441_MID_SCENARIO_ENDING_BGM": "BGM_MENU_TENRO",
	"X0441_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_MAP_FE01_01",
	"X0441_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_SERIOUS_02",
	"X0442_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_MAP_FE01_01",
	"X0443_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_MAP_FE01_01",
	"X0451_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0451_MID_SCENARIO_OPENING_BGM": "BGM_MNS_FE10_01",
	"X0452_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0453_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0461_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0461_MID_SCENARIO_OPENING_BGM": "BGM_MNS_FE08_04",
	"X0462_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0463_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0471_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0471_MID_SCENARIO_OPENING_BGM": "BGM_MNS_FE16_02",
	"X0472_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0473_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0481_MID_SCENARIO_OPENING_BGM": "BGM_MNS_FE04_01",
	"X0482_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MNS_FE14_06",
	"X0483_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"X0491_MID_SCENARIO_OPENING_BGM": "BGM_MNS_FE04_02",
	"X0492_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_MAP_FES_04",
	"X0493_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_PLAIN_03_2",
	"XX001_MID_SCENARIO_ENDING_BGM": "BGM_EVENT_SERIOUS_03",
	"XX001_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_02",
	"XX002_MID_SCENARIO_ENDING_BGM": "BGM_EVENT_SERIOUS_03",
	"XX002_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_SERIOUS_02",
	"XX003_MID_SCENARIO_OPENING_BGM": "BGM_EVENT_PLAIN_01",
	"XX004_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_01",
	"XX005_MID_SCENARIO_ENDING_BGM": "BGM_MENU_TENRO",
	"XX005_MID_SCENARIO_MAP_BEGIN_BGM": "BGM_EVENT_SERIOUS_04",
	"XX005_MID_SCENARIO_OPENING_BGM": "BGM_MENU_TENRO",
}

bgs = {
	"X0001_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0004_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0021_MID_SCENARIO_OPENING_IMAGE": "005_Castle",
	"X0023_MID_SCENARIO_ENDING_IMAGE": "005_Castle",
	"X0031_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0041_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0043_MID_SCENARIO_ENDING_IMAGE": "002_PlainForest",
	"X0051_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0061_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0063_MID_SCENARIO_ENDING_IMAGE": "001_Brave",
	"X0071_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0081_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0093_MID_SCENARIO_ENDING_IMAGE": "005_Castle",
	"X0101_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0111_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0123_MID_SCENARIO_ENDING_IMAGE": "005_Castle",
	"X0141_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0151_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0161_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0171_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0181_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0191_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0201_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0203_MID_SCENARIO_ENDING_IMAGE": "005_Castle",
	"X0211_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0213_MID_SCENARIO_ENDING_IMAGE": "005_Castle",
	"X0221_MID_SCENARIO_OPENING_IMAGE": "022_ByakuyaSummer",
	"X0231_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0241_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0251_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0261_MID_SCENARIO_OPENING_IMAGE": "022_DreameInvisibleKingdom",
	"X0262_MID_SCENARIO_OPENING_IMAGE": "022_DreameInvisibleKingdom",
	"X0263_MID_SCENARIO_ENDING_IMAGE": "022_DreameInvisibleKingdom",
	"X0263_MID_SCENARIO_OPENING_IMAGE": "022_DreameInvisibleKingdom",
	"X0271_MID_SCENARIO_OPENING_IMAGE": "013_ChristmasForest",
	"X0281_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0291_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0301_MID_SCENARIO_OPENING_IMAGE": "024_Valentine",
	"X0311_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0321_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0331_MID_SCENARIO_OPENING_IMAGE": "EvBg_BrideChurch_Outside",
	"X0341_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0351_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0361_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0371_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0381_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0391_MID_SCENARIO_OPENING_IMAGE": "013_ChristmasForest",
	"X0401_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0411_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0421_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"X0431_MID_SCENARIO_OPENING_IMAGE": "EvBg_Easter2",
	"X0441_MID_SCENARIO_ENDING_IMAGE": "EvBg__Plain30th",
	"X0441_MID_SCENARIO_OPENING_IMAGE": "EvBg__Plain30th",
	"X0451_MID_SCENARIO_OPENING_IMAGE": "EvBg_CastleJPWedding",
	"X0461_MID_SCENARIO_OPENING_IMAGE": "EvBg_Beach",
	"X0471_MID_SCENARIO_OPENING_IMAGE": "EvBg_Beach",
	"X0481_MID_SCENARIO_OPENING_IMAGE": "EvBg_TreasureIsland",
	"X0491_MID_SCENARIO_OPENING_IMAGE": "EvBg_SeisenDancehall",
	"XX001_MID_SCENARIO_ENDING_IMAGE": "005_Castle",
	"XX002_MID_SCENARIO_ENDING_IMAGE": "005_Castle",
	"XX002_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"XX003_MID_SCENARIO_OPENING_IMAGE": "001_Brave",
	"XX004_MID_SCENARIO_OPENING_IMAGE": "026_MuspelTemple",
	"XX005_MID_SCENARIO_ENDING_IMAGE": "EvBg_Chapter3_Hell",
	"XX005_MID_SCENARIO_OPENING_IMAGE": "EvBg_Chapter3_Hell",
}

dragons = {
    127: 69, 
    129: 84, 
    131: 101,
}

class UnitSide(enum.Enum):
    ALLY = 1
    ENEMY = 2
    NPC = 3

class Scenario(enum.Enum):
    OPENING = 1
    MAP_BEGIN = 2
    MAP_END = 3
    ENDING = 4

def load_unit(object: TiledObject, side: UnitSide):
    character = object.name
    if len(character) == 0:
        character = '杂兵'
    x = int(object.coordinates.x / map.tile_size.width)
    y = math.ceil(object.coordinates.y / map.tile_size.height) - 1
    if 'unit' not in object.properties:
        print('\tALLY_UNIT_JOINED({}, {}, {})'.format(character, x, y))
        return
    job = object.gid
    if job - 1 in dragons:
        return
    if job in dragons:
        job = dragons[job]
    if side == UnitSide.ALLY:
        job -= tilesets['ally'].firstgid
    if side == UnitSide.ENEMY:
        job -= tilesets['enemy'].firstgid
    if side == UnitSide.NPC:
        job -= tilesets['npc'].firstgid
    job += 1
    unit = object.properties.get('unit')
    items = unit['items'].split(',')
    items += ['0'] * (4 - len(items))
    level = unit.get('level', 1)
    autoLevel = 0
    if unit.get('autoLevel', True):
        autoLevel = 'AUTO_LEVEL'
    AI = []
    if side != UnitSide.ALLY:
        AI = [''] + ['0'] * 4
        if unit.get('heal', False):
            AI[1] = 'HealAllies'
        if not unit.get('pursue', True):
            AI[2] = 'DoNotMove'
        if unit.get('guard', False):
            AI[4] = 'GuardTile'
    print('\t{}_UNIT({}, {}, {}, {}, {}, {}, {}{})'.format(side.name, character, job, level, autoLevel, x, y, ', '.join(items), ', '.join(AI)))

def load_scenario(scenario: Scenario):
    text = '{}_MID_SCENARIO_{}'.format(map_name, scenario.name)
    bgm = text + '_BGM'
    bg = text + '_IMAGE'
    if bg in bgs:
        bg = bgs[bg]
        if bg[0].isdigit():
            bg = 'BG' + bg
        print('\tShowBG({})'.format(bg))
    if bgm in bgms:
        bgm = bgms[bgm]
        print('\tMUSC ' + bgm)
    if text in texts:
        print('\tTEX1 EvTx_' + text)
        print('\tREMA')

map_name = get_filename(sys.argv[1])
map_file = Path(sys.argv[1])
map = pytiled_parser.parse_map(map_file)
tilesets = get_tilesets(map)
layers = get_layers(map)

hasPrepScreen = map.properties is not None and map.properties.get('hasPrepScreen') == True

# definitions
print('\t#include "event.h"')
print('\t#include "chapter_id.h"')
print('\t#include "character_id.h"')
print('\t#include "class_id.h"')
print('\t#include "item_id.h"')
print('\t#include "AI.h"')
print('\t#include "background_id.h"')
print('\t#include "music_id.h"')
print('\t#include "event_text_id.h"\n')

# header
print('\t.section .rodata')
print('\t.align 2')
print('\t.global ' + map_name + 'Event')
print(map_name + 'Event:')
print('\tDefineEvents')

print('TurnBasedEvents:')
if hasPrepScreen:
    print('\tLoadMapBeginScene')
else:
    print('\tLoadBeginningScene')
print('\tEND_MAIN')

print('LocationBasedEvents:')
print('\tEND_MAIN')

print('MiscBasedEvents:')
print('\tCauseGameOverIfLordDies')
print('\tDefeatAll(EndingScene)')
print('\tEND_MAIN')

print('BeginningScene:')
load_scenario(Scenario.OPENING)
if hasPrepScreen:
    print('\tENDB')
    print('MapBeginScene:')
else:
    print('\tLOU1 EnemyUnits')
    print('\tENUN')
    print('\tLOU1 AllyUnits')
    print('\tENUN')
if '友军' in layers:
    print('\tLOU1 NPCUnits')
    print('\tENUN')
print('\tOOBB')
load_scenario(Scenario.MAP_BEGIN)
print('\tENDA')

print('EndingScene:')
load_scenario(Scenario.MAP_END)
load_scenario(Scenario.ENDING)
print('\tMNCH ' + map_name + 'Next')
print('\tENDA')

print('AllyUnits:')
layer = layers.get('我军')
if layer is not None:
    for object in layer.tiled_objects:
        load_unit(object, UnitSide.ALLY)
print('\tEND_UNIT')

print('EnemyUnits:')
layer = layers.get('敌军')
if layer is not None:
    for object in layer.tiled_objects:
        load_unit(object, UnitSide.ENEMY)
print('\tEND_UNIT')

heroes = []

layer = layers.get('友军')
if layer is not None:
    print('NPCUnits:')
    for object in layer.tiled_objects:
        load_unit(object, UnitSide.NPC)
        heroes.append(characters.romans[object.name])
    print('\tEND_UNIT')

print('CharacterBasedEvents:')
for hero in heroes:
    print('\tSelectHero({})'.format(hero))
print('\tEND_MAIN')

for hero in heroes:
    print('Select({})'.format(hero))

print('Traps:')
print('\tEND_TRAP')
