@This file is made by convert_battle_animation.py automatically. Don't edit it.
	.align 4
alfons_sharon_frames_r_header:
	.word COMP_HEAD(alfons_sharon_frames_l_header - alfons_sharon_frames_r)
alfons_sharon_frames_r:
alfons_sharon_frame_r_0:
	.word ANFRM_END_FRM
alfons_sharon_frame_r_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -9, -18, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 0, 32, -9, 14, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 32, 0, 7, -17, 1, 0, 0)
	.word ANFRM_END_FRM
alfons_sharon_frame_r_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -18, -18, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 48, 0, 14, -18, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 40, -2, 14, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 48, -10, 14, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 56, 14, 14, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 32, 0, 7, -17, 1, 0, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
	.section .rodata
	.align 4
alfons_sharon_frames_l_header:
	.word COMP_HEAD(alfons_sharon_frames_l_header - alfons_sharon_frames_r)
alfons_sharon_frames_l:
alfons_sharon_frame_l_0:
	.word ANFRM_END_FRM
alfons_sharon_frame_l_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -23, -18, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 0, 32, -23, 14, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 32, 0, -23, -17, 1, 1, 0)
	.word ANFRM_END_FRM
alfons_sharon_frame_l_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -14, -18, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 48, 0, -22, -18, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 40, -14, 14, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 48, 2, 14, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 56, -22, 14, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 32, 0, -23, -17, 1, 1, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
