@This file is made by convert_battle_animation.py automatically. Don't edit it.
	.align 4
anna_unarmed_frames_r_header:
	.word COMP_HEAD(anna_unarmed_frames_l_header - anna_unarmed_frames_r)
anna_unarmed_frames_r:
anna_unarmed_frame_r_0:
	.word ANFRM_END_FRM
anna_unarmed_frame_r_1:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 0, 0, -4, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 0, 32, -2, 0, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 0, 48, 5, -15, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 8, 48, 6, -12, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 0, 7, -10, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 16, 7, -1, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 32, 8, -8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 48, 9, -6, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 24, 0, 10, -3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 24, 16, -1, -16, 1, 0, 0)
	.word ANFRM_END_FRM
anna_unarmed_frame_r_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 40, 0, -4, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 40, 32, 21, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 48, 32, 22, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 56, 32, 23, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 64, 32, 24, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 72, 0, 25, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 24, 48, 26, -7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 72, 32, -2, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 80, 0, -2, -16, 1, 0, 0)
	.word ANFRM_END_FRM
anna_unarmed_frame_r_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 104, 32, 8, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 112, 0, 10, -15, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 32, 0, 9, -7, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 32, 48, 19, -1, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 40, 19, -15, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 48, 20, 0, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 56, 20, 1, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 40, 20, 2, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 48, 20, 3, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 56, 20, 4, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 40, 20, 5, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 48, 21, 4, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 56, 21, 5, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 40, 22, -15, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 48, 22, 5, 1, 0, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
	.section .rodata
	.align 4
anna_unarmed_frames_l_header:
	.word COMP_HEAD(anna_unarmed_frames_l_header - anna_unarmed_frames_r)
anna_unarmed_frames_l:
anna_unarmed_frame_l_0:
	.word ANFRM_END_FRM
anna_unarmed_frame_l_1:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 0, 0, -12, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 0, 32, -14, 0, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 0, 48, -13, -15, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 8, 48, -14, -12, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 0, -15, -10, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 16, -15, -1, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 32, -16, -8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 16, 48, -17, -6, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 24, 0, -18, -3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 24, 16, -15, -16, 1, 1, 0)
	.word ANFRM_END_FRM
anna_unarmed_frame_l_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 40, 0, -28, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 40, 32, -29, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 48, 32, -30, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 56, 32, -31, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 64, 32, -32, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 72, 0, -33, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 24, 48, -34, -7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 72, 32, -30, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 80, 0, -30, -16, 1, 1, 0)
	.word ANFRM_END_FRM
anna_unarmed_frame_l_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 104, 32, -40, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 112, 0, -26, -15, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 32, 0, -17, -7, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 32, 48, -27, -1, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 40, -27, -15, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 48, -28, 0, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 56, -28, 1, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 40, -28, 2, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 48, -28, 3, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 56, -28, 4, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 40, -28, 5, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 48, -29, 4, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 56, -29, 5, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 40, -30, -15, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 48, -30, 5, 1, 1, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
