@This file is made by convert_battle_animation.py automatically. Don't edit it.
	.align 4
journeyman_handaxe_frames_r_header:
	.word COMP_HEAD(journeyman_handaxe_frames_l_header - journeyman_handaxe_frames_r)
journeyman_handaxe_frames_r:
journeyman_handaxe_frame_r_0:
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_1:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 0, 0, -5, -31, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 0, 32, 11, -31, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 8, 32, -5, 1, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 48, 11, 9, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_2:
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x16, 16, 0, -26, -13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x16, 16, 16, 6, -29, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 16, 48, -10, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 24, 32, 6, -13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 32, 48, 6, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 40, 32, -10, -21, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 56, 22, -13, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 48, 0, -14, -16, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_4:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 56, 32, -7, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 72, 32, 9, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 80, 0, -39, -1, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 40, 40, -23, -9, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 48, -31, -9, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 56, 1, 15, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 8, 9, 15, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_5:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 80, 16, -5, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 48, 27, -8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 56, 27, 0, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_6:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 0, -5, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 88, 48, 27, 0, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 8, 27, -8, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_7:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 32, -5, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 96, 48, 27, 0, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 8, 27, -8, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_8:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 0, -5, -22, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 104, 48, 27, -22, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 144, 32, -5, 10, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 8, 11, 10, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_9:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 160, 32, -5, -29, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 176, 0, 11, -29, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 144, 40, -5, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 176, 32, 11, 3, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_10:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 184, 0, -5, -29, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 144, 40, -5, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 176, 48, 11, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 144, 56, 27, -21, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 152, 56, 27, -13, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_11:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 184, 32, -5, -23, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 216, 0, 27, -23, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 216, 32, -5, 9, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 216, 40, 11, 9, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_12:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 224, 0, -5, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 216, 48, 27, 0, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_13:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 232, 32, -8, -23, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 248, 32, 8, -23, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 216, 56, -8, 9, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 224, 40, 8, 9, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_14:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 0, 0, -13, -19, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 0, 32, 3, -19, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 8, 32, -13, 13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 40, 3, 13, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_15:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 16, 0, -24, -26, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 8, 48, -24, 6, 0, 0, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_r_16:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 40, 32, -5, -30, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 48, 0, 11, -30, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 24, 32, -5, 2, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 56, 0, 11, 2, 0, 0, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
	.section .rodata
	.align 4
journeyman_handaxe_frames_l_header:
	.word COMP_HEAD(journeyman_handaxe_frames_l_header - journeyman_handaxe_frames_r)
journeyman_handaxe_frames_l:
journeyman_handaxe_frame_l_0:
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_1:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 0, 0, -11, -31, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 0, 32, -19, -31, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 8, 32, -11, 1, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 48, -19, 9, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_2:
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x16, 16, 0, -6, -13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x16, 16, 16, -38, -29, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 16, 48, -6, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 24, 32, -22, -13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 32, 48, -22, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 40, 32, -6, -21, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 56, -30, -13, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 48, 0, -18, -16, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_4:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 56, 32, -9, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 72, 32, -17, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 80, 0, 7, -1, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 40, 40, 7, -9, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 48, 23, -9, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 56, -9, 15, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 8, -17, 15, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_5:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 80, 16, -27, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 48, -35, -8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 56, -35, 0, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_6:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 0, -27, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 88, 48, -35, 0, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 88, 8, -35, -8, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_7:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 32, -27, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 96, 48, -35, 0, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 8, -35, -8, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_8:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 0, -27, -22, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 104, 48, -35, -22, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 144, 32, -11, 10, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 8, -19, 10, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_9:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 160, 32, -11, -29, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 176, 0, -19, -29, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 144, 40, -11, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 176, 32, -19, 3, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_10:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 184, 0, -27, -29, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 144, 40, -11, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 176, 48, -19, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 144, 56, -35, -21, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 152, 56, -35, -13, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_11:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 184, 32, -27, -23, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 216, 0, -35, -23, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 216, 32, -11, 9, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 216, 40, -19, 9, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_12:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 224, 0, -27, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 216, 48, -35, 0, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_13:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 232, 32, -8, -23, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 248, 32, -16, -23, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 216, 56, -8, 9, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 224, 40, -16, 9, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_14:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 0, 0, -3, -19, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 0, 32, -11, -19, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 8, 32, -3, 13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 40, -11, 13, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_15:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 16, 0, -8, -26, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 8, 48, -8, 6, 0, 1, 0)
	.word ANFRM_END_FRM
journeyman_handaxe_frame_l_16:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 40, 32, -11, -30, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 48, 0, -19, -30, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 24, 32, -11, 2, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 56, 0, -19, 2, 0, 1, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
