@This file is made by convert_battle_animation.py automatically. Don't edit it.
	.align 4
pupil_magic_frames_r_header:
	.word COMP_HEAD(pupil_magic_frames_l_header - pupil_magic_frames_r)
pupil_magic_frames_r:
pupil_magic_frame_r_0:
	.word ANFRM_END_FRM
pupil_magic_frame_r_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -13, -15, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -14, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -15, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_4:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -14, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_5:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 64, 0, -13, -13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 64, 32, 3, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 48, 3, -5, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_6:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 80, 0, -13, -13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 72, 48, 3, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 56, 3, -5, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_7:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 80, 32, -13, -13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 96, 0, 3, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 56, 3, -5, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_8:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 96, 16, -12, -13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 96, 48, 4, 3, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 0, 4, -5, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_9:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 0, -16, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_10:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 112, 32, -16, -24, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 104, 48, 0, -8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 128, 32, -16, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 8, 0, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 128, 40, 0, 8, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_11:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 144, 0, -16, -23, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 128, 48, 0, -7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 136, 40, -16, 9, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 136, 48, 0, 9, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_12:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 152, 32, -20, -24, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 160, 0, -20, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 144, 48, -4, -8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 136, 56, -4, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_13:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 168, 8, -22, -24, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 168, 40, -22, 8, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_14:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 200, 0, -19, -24, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 168, 48, -19, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 160, 8, -3, -8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 144, 32, -3, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_15:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 200, 32, -19, -24, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 168, 48, -19, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 216, 0, -3, -8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 144, 32, -3, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_16:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 216, 16, -16, -23, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 216, 48, 0, -7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 168, 56, -16, 9, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 160, 24, 0, -15, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 184, 56, 0, 9, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_17:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -17, -18, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 32, -17, 14, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 40, -1, 14, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_18:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 16, 32, -12, -14, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_19:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -8, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_20:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 48, 32, -8, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_21:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -9, -14, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_22:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 80, 32, -11, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_23:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 0, -14, -14, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 48, 18, 10, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_24:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 32, -12, -17, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 56, -12, 15, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 40, 4, 15, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_25:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 128, 0, -12, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_26:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 32, -12, -15, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_27:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 160, 0, -12, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_28:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 176, 32, -12, -15, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_29:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 192, 0, -11, -14, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_30:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 232, 0, -12, -13, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 232, 32, 4, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_31:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 240, 32, -12, -15, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 224, 0, 4, 1, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 192, 0, 4, -7, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_32:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 208, 32, -14, -15, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 224, 0, 2, -15, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_33:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 224, 32, -19, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_34:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -19, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_35:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -19, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_36:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -20, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 32, 32, 12, -8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 32, 40, 12, 8, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_37:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 40, 32, -16, -13, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_38:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -18, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_39:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 72, 32, -20, -16, 0, 0, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_r_40:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 0, -16, -15, 0, 0, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
	.section .rodata
	.align 4
pupil_magic_frames_l_header:
	.word COMP_HEAD(pupil_magic_frames_l_header - pupil_magic_frames_r)
pupil_magic_frames_l:
pupil_magic_frame_l_0:
	.word ANFRM_END_FRM
pupil_magic_frame_l_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -19, -15, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -18, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -17, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_4:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -18, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_5:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 64, 0, -3, -13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 64, 32, -19, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 48, -11, -5, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_6:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 80, 0, -3, -13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 72, 48, -11, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 56, -11, -5, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_7:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 80, 32, -3, -13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 96, 0, -11, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 56, -11, -5, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_8:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 96, 16, -4, -13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 96, 48, -12, 3, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 0, -12, -5, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_9:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 0, -16, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_10:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 112, 32, 0, -24, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 104, 48, -8, -8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 128, 32, 0, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 8, -8, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 128, 40, -8, 8, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_11:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 144, 0, 0, -23, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 128, 48, -8, -7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 136, 40, 0, 9, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 136, 48, -8, 9, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_12:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 152, 32, 4, -24, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 160, 0, -12, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 144, 48, -4, -8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 136, 56, -4, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_13:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 168, 8, -10, -24, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 168, 40, -10, 8, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_14:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 200, 0, 3, -24, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 168, 48, -13, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 160, 8, -5, -8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 144, 32, -5, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_15:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 200, 32, 3, -24, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 168, 48, -13, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 216, 0, -5, -8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 144, 32, -5, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_16:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 216, 16, 0, -23, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 216, 48, -8, -7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 168, 56, 0, 9, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 160, 24, -8, -15, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 184, 56, -8, 9, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_17:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -15, -18, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 32, 1, 14, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 40, -7, 14, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_18:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 16, 32, -20, -14, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_19:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -24, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_20:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 48, 32, -24, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_21:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -23, -14, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_22:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 80, 32, -21, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_23:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 0, -18, -14, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 0, 48, -26, 10, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_24:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 32, -20, -17, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 56, -4, 15, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 8, 40, -12, 15, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_25:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 128, 0, -20, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_26:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 32, -20, -15, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_27:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 160, 0, -20, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_28:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 176, 32, -20, -15, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_29:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 192, 0, -21, -14, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_30:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 232, 0, -4, -13, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 232, 32, -12, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_31:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 240, 32, -4, -15, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 224, 0, -12, 1, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 192, 0, -12, -7, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_32:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 208, 32, -2, -15, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 224, 0, -10, -15, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_33:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 224, 32, -13, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_34:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -13, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_35:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -13, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_36:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -12, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 32, 32, -20, -8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 32, 40, -20, 8, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_37:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 40, 32, -16, -13, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_38:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -14, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_39:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 72, 32, -12, -16, 0, 1, 0)
	.word ANFRM_END_FRM
pupil_magic_frame_l_40:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 0, -16, -15, 0, 1, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
