@This file is made by convert_battle_animation.py automatically. Don't edit it.
	.align 4
rackesis_staff_frames_r_header:
	.word COMP_HEAD(rackesis_staff_frames_l_header - rackesis_staff_frames_r)
rackesis_staff_frames_r:
rackesis_staff_frame_r_0:
	.word ANFRM_END_FRM
rackesis_staff_frame_r_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -14, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -15, -15, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -17, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -16, -17, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -17, -22, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 32, -17, 4, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 40, -17, 5, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 48, -17, 6, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 56, -17, 7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 0, -16, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 8, -7, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 16, -16, -23, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 48, -14, 2, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 56, -13, 6, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 0, -13, 7, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 8, -4, 2, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 48, -4, 3, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 56, -4, 4, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 128, 0, -4, 5, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 128, 8, -4, 6, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_4:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 128, 16, -9, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 144, 0, 0, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 128, 48, -11, -5, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 136, 48, 9, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 32, -12, -15, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_5:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 160, 0, -9, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 176, 32, -10, -15, 1, 0, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
	.section .rodata
	.align 4
rackesis_staff_frames_l_header:
	.word COMP_HEAD(rackesis_staff_frames_l_header - rackesis_staff_frames_r)
rackesis_staff_frames_l:
rackesis_staff_frame_l_0:
	.word ANFRM_END_FRM
rackesis_staff_frame_l_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -18, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -17, -15, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -15, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -16, -17, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -15, -22, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 32, -15, 4, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 40, -15, 5, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 48, -15, 6, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 56, -15, 7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 0, 0, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 8, -9, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 16, -16, -23, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 48, -2, 2, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 56, -3, 6, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 0, -3, 7, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 8, -12, 2, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 48, -12, 3, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 112, 56, -12, 4, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 128, 0, -12, 5, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 128, 8, -12, 6, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_4:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 128, 16, -7, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_16x32, 144, 0, -16, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 128, 48, 3, -5, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 136, 48, -17, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 32, -20, -15, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_5:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 160, 0, -23, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 176, 32, -22, -15, 1, 1, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
