@This file is made by convert_battle_animation.py automatically. Don't edit it.
	.align 4
rackesis_staff_frames_r_header:
	.word COMP_HEAD(rackesis_staff_frames_l_header - rackesis_staff_frames_r)
rackesis_staff_frames_r:
rackesis_staff_frame_r_0:
	.word ANFRM_END_FRM
rackesis_staff_frame_r_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -14, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -15, -15, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -17, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -16, -17, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -17, -22, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 32, -17, 10, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 0, -16, -23, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 40, -8, 9, 1, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 48, 0, 9, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_4:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 96, 32, -3, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 104, 32, 5, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 72, 40, -11, 0, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 80, 40, 13, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 32, -12, -15, 1, 0, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_r_5:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 128, 0, -9, -16, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 32, -10, -15, 1, 0, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
	.section .rodata
	.align 4
rackesis_staff_frames_l_header:
	.word COMP_HEAD(rackesis_staff_frames_l_header - rackesis_staff_frames_r)
rackesis_staff_frames_l:
rackesis_staff_frame_l_0:
	.word ANFRM_END_FRM
rackesis_staff_frame_l_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -18, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 32, -17, -15, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -15, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 32, -16, -17, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 64, 0, -15, -22, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 32, -15, 10, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 96, 0, -16, -23, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 40, 0, 9, 1, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 48, -8, 9, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_4:
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 96, 32, -5, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x32, 104, 32, -13, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 72, 40, 3, 0, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_TALL, ATTR1_SIZE_8x16, 80, 40, -21, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 112, 32, -20, -15, 1, 1, 0)
	.word ANFRM_END_FRM
rackesis_staff_frame_l_5:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 128, 0, -23, -16, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 144, 32, -22, -15, 1, 1, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
