@This file is made by convert_battle_animation.py automatically. Don't edit it.
	.align 4
sharon_unarmed_frames_r_header:
	.word COMP_HEAD(sharon_unarmed_frames_l_header - sharon_unarmed_frames_r)
sharon_unarmed_frames_r:
sharon_unarmed_frame_r_0:
	.word ANFRM_END_FRM
sharon_unarmed_frame_r_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -14, -19, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 0, 32, 3, -2, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 0, 48, -14, 7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 56, -6, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 16, 32, 3, 8, 0, 0, 0)
	.word ANFRM_END_FRM
sharon_unarmed_frame_r_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -14, -19, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 16, 40, -14, 6, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 16, 56, -14, 7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 32, 32, -6, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 32, 48, 3, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 40, 48, 4, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 32, 5, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 40, 6, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 48, 7, 8, 0, 0, 0)
	.word ANFRM_END_FRM
sharon_unarmed_frame_r_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 56, 32, -14, -19, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 0, -14, 6, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 8, -14, 7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 64, 16, -6, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 56, 3, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 24, 4, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 24, 5, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 16, 6, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 24, 7, 8, 0, 0, 0)
	.word ANFRM_END_FRM
sharon_unarmed_frame_r_4:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 88, 16, -14, -19, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 88, 48, -14, 6, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 88, 56, -14, 7, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 0, -6, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 8, 3, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 8, 4, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 112, 0, 5, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 112, 8, 6, 8, 0, 0, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 120, 0, 7, 8, 0, 0, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
	.section .rodata
	.align 4
sharon_unarmed_frames_l_header:
	.word COMP_HEAD(sharon_unarmed_frames_l_header - sharon_unarmed_frames_r)
sharon_unarmed_frames_l:
sharon_unarmed_frame_l_0:
	.word ANFRM_END_FRM
sharon_unarmed_frame_l_1:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 0, 0, -18, -19, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_16x16, 0, 32, -19, -2, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 0, 48, -18, 7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 0, 56, -10, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 16, 32, -19, 8, 0, 1, 0)
	.word ANFRM_END_FRM
sharon_unarmed_frame_l_2:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 32, 0, -18, -19, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 16, 40, -18, 6, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 16, 56, -18, 7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 32, 32, -10, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 32, 48, -11, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 40, 48, -12, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 32, -13, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 40, -14, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 48, -15, 8, 0, 1, 0)
	.word ANFRM_END_FRM
sharon_unarmed_frame_l_3:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 56, 32, -18, -19, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 0, -18, 6, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 64, 8, -18, 7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 64, 16, -10, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 48, 56, -11, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 64, 24, -12, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 72, 24, -13, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 16, -14, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 80, 24, -15, 8, 0, 1, 0)
	.word ANFRM_END_FRM
sharon_unarmed_frame_l_4:
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_32x32, 88, 16, -18, -19, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 88, 48, -18, 6, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_32x8, 88, 56, -18, 7, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_WIDE, ATTR1_SIZE_16x8, 96, 0, -10, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 96, 8, -11, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 104, 8, -12, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 112, 0, -13, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 112, 8, -14, 8, 0, 1, 0)
	.hword ANFRM_OBJ(ATTR0_SQUARE, ATTR1_SIZE_8x8, 120, 0, -15, 8, 0, 1, 0)
	.word ANFRM_END_FRM

	.word ANFRM_END_ALL
