// Generated by tool/font/export_font_en.py.

#include <tonc.h>

#include "common.h"

#include "font.h"

#include "font_jp_black.h"
#include "font_cn_black.h"
#include "font_en_black.h"

const struct Glyph blackFont1F = {
	NULL,
	0,
	0,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont20 = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont21 = {
	NULL,
	0,
	3,
	{0, 0, 0, 47, 47, 47, 47, 11, 11, 11, 11, 0, 11, 11, 0, 0},
};

const struct Glyph blackFont22 = {
	NULL,
	0,
	5,
	{0, 975, 975, 910, 715, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont23 = {
	NULL,
	0,
	8,
	{0, 0, 0, 11440, 11440, 11440, 49148, 11960, 11820, 2860, 12287, 2988, 2860, 2860, 0, 0},
};

const struct Glyph blackFont24 = {
	NULL,
	0,
	6,
	{0, 0, 0, 176, 764, 3003, 2995, 187, 252, 2992, 3003, 3003, 764, 176, 0, 0},
};

const struct Glyph blackFont25 = {
	NULL,
	0,
	8,
	{0, 0, 0, 46, 45243, 11443, 11451, 2862, 704, 11952, 47916, 45868, 47883, 11776, 0, 0},
};

const struct Glyph blackFont26 = {
	NULL,
	0,
	7,
	{0, 0, 0, 752, 2988, 2860, 2860, 2988, 752, 13036, 15118, 11779, 15371, 15356, 0, 0},
};

const struct Glyph blackFont27 = {
	NULL,
	0,
	2,
	{0, 15, 14, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont28 = {
	NULL,
	0,
	4,
	{0, 0, 0, 176, 44, 46, 11, 11, 11, 11, 11, 46, 44, 176, 0, 0},
};

const struct Glyph blackFont29 = {
	NULL,
	0,
	4,
	{0, 0, 0, 11, 46, 44, 184, 176, 176, 176, 184, 44, 46, 11, 0, 0},
};

const struct Glyph blackFont2A = {
	NULL,
	0,
	8,
	{0, 0, 0, 0, 704, 704, 45771, 12012, 3056, 3056, 12012, 45771, 704, 704, 0, 0},
};

const struct Glyph blackFont2B = {
	NULL,
	0,
	8,
	{0, 0, 0, 704, 704, 704, 704, 704, 49151, 43754, 704, 704, 704, 704, 0, 0},
};

const struct Glyph blackFont2C = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 15, 14, 11},
};

const struct Glyph blackFont2D = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 170, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont2E = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0},
};

const struct Glyph blackFont2F = {
	NULL,
	0,
	7,
	{0, 0, 11264, 11264, 2816, 2816, 704, 704, 176, 176, 44, 44, 11, 11, 0, 0},
};

const struct Glyph blackFont30 = {
	NULL,
	0,
	6,
	{0, 0, 0, 764, 2987, 2827, 2827, 2827, 2827, 2827, 2827, 2827, 2987, 764, 0, 0},
};

const struct Glyph blackFont31 = {
	NULL,
	0,
	4,
	{0, 0, 0, 176, 191, 186, 176, 176, 176, 176, 176, 176, 176, 176, 0, 0},
};

const struct Glyph blackFont32 = {
	NULL,
	0,
	6,
	{0, 0, 0, 764, 2987, 2827, 2827, 2944, 736, 184, 44, 46, 2731, 3071, 0, 0},
};

const struct Glyph blackFont33 = {
	NULL,
	0,
	6,
	{0, 0, 0, 764, 2987, 2827, 2816, 764, 2984, 2816, 2827, 2827, 2987, 764, 0, 0},
};

const struct Glyph blackFont34 = {
	NULL,
	0,
	7,
	{0, 0, 0, 3008, 3008, 2992, 2992, 2860, 2860, 2827, 16383, 11178, 2816, 2816, 0, 0},
};

const struct Glyph blackFont35 = {
	NULL,
	0,
	6,
	{0, 0, 0, 1023, 683, 11, 11, 767, 2987, 2816, 2827, 2827, 2987, 764, 0, 0},
};

const struct Glyph blackFont36 = {
	NULL,
	0,
	6,
	{0, 0, 0, 764, 2987, 2827, 11, 767, 2987, 2827, 2827, 2827, 2987, 764, 0, 0},
};

const struct Glyph blackFont37 = {
	NULL,
	0,
	6,
	{0, 0, 0, 3071, 2986, 2944, 2944, 704, 704, 176, 176, 176, 176, 176, 0, 0},
};

const struct Glyph blackFont38 = {
	NULL,
	0,
	6,
	{0, 0, 0, 764, 2987, 2827, 2827, 764, 2987, 2827, 2827, 2827, 2987, 764, 0, 0},
};

const struct Glyph blackFont39 = {
	NULL,
	0,
	6,
	{0, 0, 0, 764, 2987, 2827, 2827, 2827, 3070, 2984, 2816, 2827, 2987, 764, 0, 0},
};

const struct Glyph blackFont3A = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 11, 11, 0, 0, 0},
};

const struct Glyph blackFont3B = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 0, 15, 15, 0, 0, 0, 15, 15, 14, 11, 0},
};

const struct Glyph blackFont3C = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 2816, 704, 176, 44, 11, 11, 44, 176, 704, 2816, 0, 0},
};

const struct Glyph blackFont3D = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 3071, 2730, 0, 3071, 2730, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont3E = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 11, 44, 176, 704, 2816, 2816, 704, 176, 44, 11, 0, 0},
};

const struct Glyph blackFont3F = {
	NULL,
	0,
	7,
	{0, 0, 0, 752, 2988, 11275, 11275, 2816, 192, 176, 176, 0, 176, 176, 0, 0},
};

const struct Glyph blackFont40 = {
	NULL,
	0,
	8,
	{0, 0, 0, 3056, 11308, 45771, 46003, 45875, 45875, 45875, 48051, 48891, 11276, 3056, 0, 0},
};

const struct Glyph blackFont41 = {
	NULL,
	0,
	6,
	{0, 0, 0, 176, 236, 748, 907, 2827, 2827, 3071, 2987, 2827, 2827, 2827, 0, 0},
};

const struct Glyph blackFont42 = {
	NULL,
	0,
	6,
	{0, 0, 0, 767, 2987, 2827, 2827, 767, 939, 2827, 2827, 2827, 2827, 767, 0, 0},
};

const struct Glyph blackFont43 = {
	NULL,
	0,
	6,
	{0, 0, 0, 764, 2987, 2827, 11, 11, 11, 11, 11, 2827, 2827, 764, 0, 0},
};

const struct Glyph blackFont44 = {
	NULL,
	0,
	6,
	{0, 0, 0, 63, 235, 715, 907, 2827, 2827, 2827, 907, 715, 235, 63, 0, 0},
};

const struct Glyph blackFont45 = {
	NULL,
	0,
	6,
	{0, 0, 0, 3071, 2731, 11, 11, 767, 683, 11, 11, 11, 2731, 3071, 0, 0},
};

const struct Glyph blackFont46 = {
	NULL,
	0,
	6,
	{0, 0, 0, 3071, 2731, 11, 11, 767, 683, 11, 11, 11, 11, 11, 0, 0},
};

const struct Glyph blackFont47 = {
	NULL,
	0,
	6,
	{0, 0, 0, 176, 748, 2827, 2827, 11, 11, 3019, 2827, 2827, 3052, 3000, 0, 0},
};

const struct Glyph blackFont48 = {
	NULL,
	0,
	6,
	{0, 0, 0, 2827, 2827, 2827, 2827, 2827, 3071, 2987, 2827, 2827, 2827, 2827, 0, 0},
};

const struct Glyph blackFont49 = {
	NULL,
	0,
	4,
	{0, 0, 0, 191, 44, 44, 44, 44, 44, 44, 44, 44, 44, 191, 0, 0},
};

const struct Glyph blackFont4A = {
	NULL,
	0,
	6,
	{0, 0, 0, 2816, 2816, 2816, 2816, 2816, 2816, 2827, 2827, 2827, 750, 184, 0, 0},
};

const struct Glyph blackFont4B = {
	NULL,
	0,
	6,
	{0, 0, 0, 2827, 2955, 715, 235, 59, 47, 179, 707, 707, 2819, 2819, 0, 0},
};

const struct Glyph blackFont4C = {
	NULL,
	0,
	5,
	{0, 0, 0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 683, 767, 0, 0},
};

const struct Glyph blackFont4D = {
	NULL,
	0,
	8,
	{0, 0, 0, 45067, 47115, 48143, 48687, 47931, 48059, 48059, 48059, 45803, 45771, 45771, 0, 0},
};

const struct Glyph blackFont4E = {
	NULL,
	0,
	6,
	{0, 0, 0, 2827, 2827, 2863, 2863, 3003, 3003, 3051, 3019, 2955, 2955, 2827, 0, 0},
};

const struct Glyph blackFont4F = {
	NULL,
	0,
	6,
	{0, 0, 0, 176, 748, 907, 2827, 2827, 2827, 2827, 2827, 907, 748, 176, 0, 0},
};

const struct Glyph blackFont50 = {
	NULL,
	0,
	6,
	{0, 0, 0, 191, 747, 2955, 2827, 2955, 747, 191, 43, 11, 11, 11, 0, 0},
};

const struct Glyph blackFont51 = {
	NULL,
	0,
	7,
	{0, 0, 0, 752, 2988, 11819, 11787, 11275, 11275, 11451, 12015, 2988, 3056, 11264, 0, 0},
};

const struct Glyph blackFont52 = {
	NULL,
	0,
	6,
	{0, 0, 0, 191, 747, 2955, 2827, 2955, 747, 191, 715, 715, 2827, 2827, 0, 0},
};

const struct Glyph blackFont53 = {
	NULL,
	0,
	7,
	{0, 0, 0, 760, 2990, 11787, 11787, 44, 752, 2816, 11275, 11787, 2990, 760, 0, 0},
};

const struct Glyph blackFont54 = {
	NULL,
	0,
	6,
	{0, 0, 0, 3071, 2746, 176, 176, 176, 176, 176, 176, 176, 176, 176, 0, 0},
};

const struct Glyph blackFont55 = {
	NULL,
	0,
	6,
	{0, 0, 0, 2827, 2827, 2827, 2827, 2827, 2827, 2827, 2827, 2987, 748, 176, 0, 0},
};

const struct Glyph blackFont56 = {
	NULL,
	0,
	6,
	{0, 0, 0, 2827, 2827, 2827, 2827, 2827, 718, 748, 748, 184, 176, 176, 0, 0},
};

const struct Glyph blackFont57 = {
	NULL,
	0,
	8,
	{0, 0, 0, 45771, 45771, 45771, 45771, 48059, 48059, 48059, 48059, 11820, 11308, 11308, 0, 0},
};

const struct Glyph blackFont58 = {
	NULL,
	0,
	6,
	{0, 0, 0, 2827, 2955, 748, 748, 176, 176, 184, 748, 750, 2955, 2827, 0, 0},
};

const struct Glyph blackFont59 = {
	NULL,
	0,
	6,
	{0, 0, 0, 2827, 2827, 2955, 718, 748, 748, 176, 176, 176, 176, 176, 0, 0},
};

const struct Glyph blackFont5A = {
	NULL,
	0,
	6,
	{0, 0, 0, 3071, 2986, 2816, 704, 192, 176, 44, 44, 11, 2731, 3071, 0, 0},
};

const struct Glyph blackFont5B = {
	NULL,
	0,
	3,
	{0, 0, 0, 47, 43, 11, 11, 11, 11, 11, 11, 11, 11, 47, 0, 0},
};

const struct Glyph blackFont5C = {
	NULL,
	0,
	8,
	{0, 0, 0, 45067, 11308, 2992, 704, 49151, 704, 49151, 704, 704, 704, 704, 0, 0},
};

const struct Glyph blackFont5D = {
	NULL,
	0,
	3,
	{0, 0, 0, 47, 46, 44, 44, 44, 44, 44, 44, 44, 44, 47, 0, 0},
};

const struct Glyph blackFont5E = {
	NULL,
	0,
	5,
	{0, 190, 747, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont5F = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 191, 0, 0, 0},
};

const struct Glyph blackFont60 = {
	NULL,
	0,
	2,
	{0, 12, 11, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph blackFont61 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 188, 715, 752, 748, 715, 715, 747, 3004, 0, 0},
};

const struct Glyph blackFont62 = {
	NULL,
	0,
	5,
	{0, 0, 0, 11, 11, 11, 11, 191, 747, 715, 715, 715, 747, 191, 0, 0},
};

const struct Glyph blackFont63 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 188, 747, 715, 11, 11, 715, 747, 188, 0, 0},
};

const struct Glyph blackFont64 = {
	NULL,
	0,
	5,
	{0, 0, 0, 704, 704, 704, 704, 764, 747, 715, 715, 715, 715, 766, 0, 0},
};

const struct Glyph blackFont65 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 188, 747, 715, 767, 171, 715, 747, 188, 0, 0},
};

const struct Glyph blackFont66 = {
	NULL,
	0,
	5,
	{0, 0, 0, 176, 172, 44, 44, 767, 686, 44, 44, 44, 44, 44, 0, 0},
};

const struct Glyph blackFont67 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 0, 0, 752, 2988, 2860, 2988, 764, 172, 3068, 11275, 11951, 3068},
};

const struct Glyph blackFont68 = {
	NULL,
	0,
	5,
	{0, 0, 0, 11, 11, 11, 11, 187, 751, 719, 715, 715, 715, 715, 0, 0},
};

const struct Glyph blackFont69 = {
	NULL,
	0,
	2,
	{0, 0, 0, 11, 11, 0, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0},
};

const struct Glyph blackFont6A = {
	NULL,
	0,
	3,
	{0, 0, 0, 44, 44, 0, 44, 44, 44, 44, 44, 44, 44, 44, 46, 11},
};

const struct Glyph blackFont6B = {
	NULL,
	0,
	5,
	{0, 0, 0, 11, 11, 11, 11, 715, 187, 47, 187, 187, 715, 715, 0, 0},
};

const struct Glyph blackFont6C = {
	NULL,
	0,
	2,
	{0, 0, 0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0},
};

const struct Glyph blackFont6D = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 751, 3003, 2867, 2867, 2867, 2867, 2867, 2867, 0, 0},
};

const struct Glyph blackFont6E = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 187, 751, 715, 715, 715, 715, 715, 715, 0, 0},
};

const struct Glyph blackFont6F = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 188, 747, 715, 715, 715, 715, 747, 188, 0, 0},
};

const struct Glyph blackFont70 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 191, 747, 715, 715, 715, 715, 747, 191, 11, 11},
};

const struct Glyph blackFont71 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 764, 747, 715, 715, 715, 715, 747, 764, 704, 704},
};

const struct Glyph blackFont72 = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 187, 47, 11, 11, 11, 11, 11, 11, 0, 0},
};

const struct Glyph blackFont73 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 188, 747, 11, 44, 176, 704, 747, 188, 0, 0},
};

const struct Glyph blackFont74 = {
	NULL,
	0,
	5,
	{0, 0, 0, 44, 44, 44, 44, 767, 686, 44, 44, 44, 172, 184, 0, 0},
};

const struct Glyph blackFont75 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 715, 715, 715, 715, 715, 715, 747, 764, 0, 0},
};

const struct Glyph blackFont76 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 2827, 2827, 2955, 748, 748, 748, 176, 176, 0, 0},
};

const struct Glyph blackFont77 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 2867, 2867, 2867, 2867, 3003, 3003, 748, 716, 0, 0},
};

const struct Glyph blackFont78 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 2955, 2955, 750, 184, 184, 750, 2955, 2955, 0, 0},
};

const struct Glyph blackFont79 = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 179, 179, 179, 179, 187, 190, 176, 176, 186, 47},
};

const struct Glyph blackFont7A = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 767, 746, 176, 184, 44, 46, 683, 767, 0, 0},
};

const struct Glyph blackFont7B = {
	NULL,
	0,
	4,
	{0, 0, 0, 176, 44, 44, 44, 44, 11, 11, 44, 44, 44, 176, 0, 0},
};

const struct Glyph blackFont7C = {
	NULL,
	0,
	2,
	{0, 0, 0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0},
};

const struct Glyph blackFont7D = {
	NULL,
	0,
	4,
	{0, 0, 0, 11, 46, 44, 44, 44, 176, 176, 44, 44, 46, 11, 0, 0},
};

const struct Glyph blackFont7E = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 0, 0, 0, 60, 15083, 12162, 2560, 0, 0, 0, 0, 0},
};

const struct Glyph * const blackFonts[] = {
	&blackFontList40,
	&blackFontList41,
	&blackFontList42,
	&blackFontList43,
	&blackFontList44,
	&blackFontList45,
	&blackFontList46,
	&blackFontList47,
	&blackFontList48,
	&blackFontList49,
	&blackFontList4A,
	&blackFontList4B,
	&blackFontList4C,
	&blackFontList4D,
	&blackFontList4E,
	&blackFontList4F,
	&blackFontList50,
	&blackFontList51,
	&blackFontList52,
	&blackFontList53,
	&blackFontList54,
	&blackFontList55,
	&blackFontList56,
	&blackFontList57,
	&blackFontList58,
	&blackFontList59,
	&blackFontList5A,
	&blackFontList5B,
	&blackFontList5C,
	&blackFontList5D,
	&blackFontList5E,
	&blackFontList5F,
	&blackFontList60,
	&blackFontList61,
	&blackFontList62,
	&blackFontList63,
	&blackFontList64,
	&blackFontList65,
	&blackFontList66,
	&blackFontList67,
	&blackFontList68,
	&blackFontList69,
	&blackFontList6A,
	&blackFontList6B,
	&blackFontList6C,
	&blackFontList6D,
	&blackFontList6E,
	&blackFontList6F,
	&blackFontList70,
	&blackFontList71,
	&blackFontList72,
	&blackFontList73,
	&blackFontList74,
	&blackFontList75,
	&blackFontList76,
	&blackFontList77,
	&blackFontList78,
	&blackFontList79,
	&blackFontList7A,
	&blackFontList7B,
	&blackFontList7C,
	&blackFontList7D,
	&blackFontList7E,
	NULL, // 7F
	&blackFontList80,
	&blackFontList81,
	&blackFontList82,
	&blackFontList83,
	&blackFontList84,
	&blackFontList85,
	&blackFontList86,
	&blackFontList87,
	&blackFontList88,
	&blackFontList89,
	&blackFontList8A,
	&blackFontList8B,
	&blackFontList8C,
	&blackFontList8D,
	&blackFontList8E,
	&blackFontList8F,
	&blackFontList90,
	&blackFontList91,
	&blackFontList92,
	&blackFontList93,
	&blackFontList94,
	&blackFontList95,
	&blackFontList96,
	&blackFontList97,
	&blackFontList98,
	&blackFontList99,
	&blackFontList9A,
	&blackFontList9B,
	&blackFontList9C,
	&blackFontList9D,
	&blackFontList9E,
	&blackFontList9F,
	&blackFontListA0,
	&blackFontListA1,
	&blackFontListA2,
	&blackFontListA3,
	&blackFontListA4,
	&blackFontListA5,
	&blackFontListA6,
	&blackFontListA7,
	&blackFontListA8,
	&blackFontListA9,
	&blackFontListAA,
	&blackFontListAB,
	&blackFontListAC,
	&blackFontListAD,
	&blackFontListAE,
	&blackFontListAF,
	&blackFontListB0,
	&blackFontListB1,
	&blackFontListB2,
	&blackFontListB3,
	&blackFontListB4,
	&blackFontListB5,
	&blackFontListB6,
	&blackFontListB7,
	&blackFontListB8,
	&blackFontListB9,
	&blackFontListBA,
	&blackFontListBB,
	&blackFontListBC,
	&blackFontListBD,
	&blackFontListBE,
	&blackFontListBF,
	&blackFontListC0,
	&blackFontListC1,
	&blackFontListC2,
	&blackFontListC3,
	&blackFontListC4,
	&blackFontListC5,
	&blackFontListC6,
	&blackFontListC7,
	&blackFontListC8,
	&blackFontListC9,
	&blackFontListCA,
	&blackFontListCB,
	&blackFontListCC,
	&blackFontListCD,
	&blackFontListCE,
	&blackFontListCF,
	&blackFontListD0,
	&blackFontListD1,
	&blackFontListD2,
	&blackFontListD3,
	&blackFontListD4,
	&blackFontListD5,
	&blackFontListD6,
	&blackFontListD7,
	&blackFontListD8,
	&blackFontListD9,
	&blackFontListDA,
	&blackFontListDB,
	&blackFontListDC,
	&blackFontListDD,
	&blackFontListDE,
	&blackFontListDF,
	&blackFontListE0,
	&blackFontListE1,
	&blackFontListE2,
	&blackFontListE3,
	&blackFontListE4,
	&blackFontListE5,
	&blackFontListE6,
	&blackFontListE7,
	&blackFontListE8,
	&blackFontListE9,
	&blackFontListEA,
	&blackFontListEB,
	&blackFontListEC,
	&blackFontListED,
	&blackFontListEE,
	&blackFontListEF,
	&blackFontListF0,
	&blackFontListF1,
	&blackFontListF2,
	&blackFontListF3,
	&blackFontListF4,
	&blackFontListF5,
	&blackFontListF6,
	&blackFontListF7,
	&blackFontListF8,
	&blackFontListF9,
	&blackFontListFA,
	&blackFontListFB,
	&blackFontListFC,
	&blackFontGbFDA3,
	&blackFontGbFEA3,
	NULL, // FF

	NULL, // 0
	NULL, // 1
	NULL, // 2
	NULL, // 3
	NULL, // 4
	NULL, // 5
	NULL, // 6
	NULL, // 7
	NULL, // 8
	NULL, // 9
	NULL, // A
	NULL, // B
	NULL, // C
	NULL, // D
	NULL, // E
	NULL, // F
	NULL, // 10
	NULL, // 11
	NULL, // 12
	NULL, // 13
	NULL, // 14
	NULL, // 15
	NULL, // 16
	NULL, // 17
	NULL, // 18
	NULL, // 19
	NULL, // 1A
	NULL, // 1B
	NULL, // 1C
	NULL, // 1D
	NULL, // 1E
	&blackFont1F,
	&blackFont20,
	&blackFont21,
	&blackFont22,
	&blackFont23,
	&blackFont24,
	&blackFont25,
	&blackFont26,
	&blackFont27,
	&blackFont28,
	&blackFont29,
	&blackFont2A,
	&blackFont2B,
	&blackFont2C,
	&blackFont2D,
	&blackFont2E,
	&blackFont2F,
	&blackFont30,
	&blackFont31,
	&blackFont32,
	&blackFont33,
	&blackFont34,
	&blackFont35,
	&blackFont36,
	&blackFont37,
	&blackFont38,
	&blackFont39,
	&blackFont3A,
	&blackFont3B,
	&blackFont3C,
	&blackFont3D,
	&blackFont3E,
	&blackFont3F,
	&blackFont40,
	&blackFont41,
	&blackFont42,
	&blackFont43,
	&blackFont44,
	&blackFont45,
	&blackFont46,
	&blackFont47,
	&blackFont48,
	&blackFont49,
	&blackFont4A,
	&blackFont4B,
	&blackFont4C,
	&blackFont4D,
	&blackFont4E,
	&blackFont4F,
	&blackFont50,
	&blackFont51,
	&blackFont52,
	&blackFont53,
	&blackFont54,
	&blackFont55,
	&blackFont56,
	&blackFont57,
	&blackFont58,
	&blackFont59,
	&blackFont5A,
	&blackFont5B,
	&blackFont5C,
	&blackFont5D,
	&blackFont5E,
	&blackFont5F,
	&blackFont60,
	&blackFont61,
	&blackFont62,
	&blackFont63,
	&blackFont64,
	&blackFont65,
	&blackFont66,
	&blackFont67,
	&blackFont68,
	&blackFont69,
	&blackFont6A,
	&blackFont6B,
	&blackFont6C,
	&blackFont6D,
	&blackFont6E,
	&blackFont6F,
	&blackFont70,
	&blackFont71,
	&blackFont72,
	&blackFont73,
	&blackFont74,
	&blackFont75,
	&blackFont76,
	&blackFont77,
	&blackFont78,
	&blackFont79,
	&blackFont7A,
	&blackFont7B,
	&blackFont7C,
	&blackFont7D,
	&blackFont7E,
	NULL, // 7F
	NULL, // 0
	NULL, // 1
	NULL, // 2
	NULL, // 3
	NULL, // 4
	NULL, // 5
	NULL, // 6
	NULL, // 7
	NULL, // 8
	NULL, // 9
	NULL, // A
	NULL, // B
	NULL, // C
	NULL, // D
	NULL, // E
	NULL, // F
	NULL, // 10
	NULL, // 11
	NULL, // 12
	NULL, // 13
	NULL, // 14
	NULL, // 15
	NULL, // 16
	NULL, // 17
	NULL, // 18
	NULL, // 19
	NULL, // 1A
	NULL, // 1B
	NULL, // 1C
	NULL, // 1D
	NULL, // 1E
	&blackFont1F,
	&Sglyph_shortspace, // 20
	&blackFont21,
	&Sglyph_DoubleQuote, // 22
	&blackFont23,
	&blackFont24,
	&blackFont25,
	&blackFont26,
	&Sglyph_SingleQuote, // 27
	&Sglyph_LParen, // 28
	&Sglyph_RParen, // 29
	&blackFont2A,
	&Sglyph_Plus, // 2B
	&Sglyph_Comma, // 2C
	&Sglyph_Minus, // 2D
	&Sglyph_Dot, // 2E
	&Sglyph_Slash, // 2F
	&Sglyph_0,
	&Sglyph_1,
	&Sglyph_2,
	&Sglyph_3,
	&Sglyph_4,
	&Sglyph_5,
	&Sglyph_6,
	&Sglyph_7,
	&Sglyph_8,
	&Sglyph_9,
	&blackFont3A,
	&Sglyph_Colon, // 3B
	&blackFont3C,
	&blackFont3D,
	&blackFont3E,
	&blackFont3F,
	&blackFont40,
	&UpSglyph_a, // 41
	&UpSglyph_b, // 42
	&UpSglyph_c, // 43
	&UpSglyph_d, // 44
	&UpSglyph_e, // 45
	&UpSglyph_f, // 46
	&UpSglyph_g, // 47
	&UpSglyph_h, // 48
	&blackFont49,
	&UpSglyph_j, // 4A
	&UpSglyph_k, // 4B
	&UpSglyph_l, // 4C
	&blackFont4D,
	&blackFont4E,
	&UpSglyph_o, // 4F
	&UpSglyph_p, // 50
	&UpSglyph_q, // 51
	&UpSglyph_r, // 52
	&UpSglyph_s, // 53
	&blackFont54,
	&UpSglyph_u, // 55
	&UpSglyph_v, // 56
	&blackFont57,
	&UpSglyph_x, // 58
	&UpSglyph_y, // 59
	&UpSglyph_z, // 5A
	&blackFont5B,
	&blackFont5C,
	&blackFont5D,
	&blackFont5E,
	&blackFont5F,
	&blackFont60,
	&Sglyph_a, // 61
	&Sglyph_b, // 62
	&Sglyph_c, // 63
	&Sglyph_d, // 64
	&Sglyph_e, // 65
	&Sglyph_f, // 66
	&Sglyph_g, // 67
	&Sglyph_h, // 68
	&blackFont69,
	&blackFont6A,
	&Sglyph_k, // 6B
	&blackFont6C,
	&blackFont6D,
	&Sglyph_n, // 6E
	&Sglyph_o, // 6F
	&Sglyph_p, // 70
	&Sglyph_q, // 71
	&Sglyph_r, // 72
	&Sglyph_s, // 73
	&Sglyph_t, // 74
	&Sglyph_u, // 75
	&Sglyph_v, // 76
	&blackFont77,
	&Sglyph_x, // 78
	&Sglyph_y, // 79
	&Sglyph_z, // 7A
	&blackFont7B,
	&blackFont7C,
	&blackFont7D,
	&blackFont7E,
	NULL,
};

const struct Glyph * const * const pBlackFonts = &blackFonts[0];
