// Generated by tool/font/export_font_en.py.

#include <tonc.h>

#include "common.h"

#include "font.h"

#include "font_jp_white.h"
#include "font_cn_white.h"

const struct Glyph whiteFont1F = {
	NULL,
	0,
	0,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont20 = {
	NULL,
	0,
	3,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont21 = {
	NULL,
	0,
	4,
	{0, 0, 0, 240, 940, 940, 940, 236, 236, 236, 48, 236, 236, 48, 0, 0},
};

const struct Glyph whiteFont22 = {
	NULL,
	0,
	4,
	{0, 0, 204, 955, 955, 238, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont23 = {
	NULL,
	0,
	6,
	{0, 0, 0, 816, 3820, 3820, 15019, 3820, 3820, 3820, 15019, 3820, 3820, 816, 0, 0},
};

const struct Glyph whiteFont24 = {
	NULL,
	0,
	6,
	{0, 0, 0, 192, 944, 3756, 15291, 16315, 3756, 15292, 15291, 3756, 944, 192, 0, 0},
};

const struct Glyph whiteFont25 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 252, 871, 4027, 15291, 3687, 4028, 13932, 15291, 15295, 13936, 4032, 0},
};

const struct Glyph whiteFont26 = {
	NULL,
	0,
	6,
	{0, 0, 0, 252, 871, 955, 955, 4027, 15340, 15291, 14075, 14075, 15271, 15612, 0, 0},
};

const struct Glyph whiteFont27 = {
	NULL,
	0,
	2,
	{0, 0, 12, 59, 59, 14, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont28 = {
	NULL,
	0,
	4,
	{0, 0, 192, 944, 236, 236, 59, 59, 59, 59, 236, 236, 944, 192, 0, 0},
};

const struct Glyph whiteFont29 = {
	NULL,
	0,
	4,
	{0, 0, 12, 59, 236, 236, 944, 944, 944, 944, 236, 236, 59, 12, 0, 0},
};

const struct Glyph whiteFont2A = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 192, 4028, 15291, 3756, 944, 3756, 15291, 4028, 192, 0, 0, 0},
};

const struct Glyph whiteFont2B = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 192, 944, 944, 4028, 15019, 4028, 944, 944, 192, 0, 0, 0},
};

const struct Glyph whiteFont2C = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 59, 59, 14, 3},
};

const struct Glyph whiteFont2D = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 0, 252, 939, 252, 0, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont2E = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 59, 12, 0, 0},
};

const struct Glyph whiteFont2F = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 768, 3776, 3776, 944, 944, 236, 236, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont30 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 4032, 15024, 60396, 60395, 60395, 60395, 60395, 15339, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont31 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 768, 3824, 3756, 3760, 3760, 3760, 3760, 16060, 60075, 16380, 0, 0},
};

const struct Glyph whiteFont32 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 4080, 15020, 60395, 60219, 15116, 3776, 13232, 61420, 60075, 16380, 0, 0},
};

const struct Glyph whiteFont33 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 16368, 60076, 15355, 3788, 15024, 60400, 60396, 15339, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont34 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 3072, 15104, 15040, 15024, 15084, 60155, 15019, 15100, 60080, 16320, 0, 0},
};

const struct Glyph whiteFont35 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 12336, 61420, 15020, 4076, 15020, 60400, 60396, 15339, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont36 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 4032, 15024, 4076, 4076, 15019, 60395, 60395, 15339, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont37 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 16368, 60076, 15355, 15116, 3776, 3776, 3760, 3760, 944, 192, 0, 0},
};

const struct Glyph whiteFont38 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 1008, 3756, 15355, 15355, 3756, 15020, 60411, 15355, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont39 = {
	NULL,
	0,
	7,
	{0, 0, 0, 0, 4032, 15024, 60396, 60395, 60395, 60076, 60400, 15344, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont3A = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 12, 59, 12, 0, 0, 12, 59, 12, 0, 0, 0},
};

const struct Glyph whiteFont3B = {
	NULL,
	0,
	2,
	{0, 0, 0, 0, 0, 12, 59, 12, 0, 0, 12, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont3C = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 3840, 3776, 944, 236, 59, 236, 944, 3776, 3840, 0, 0, 0},
};

const struct Glyph whiteFont3D = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 252, 939, 252, 252, 939, 252, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont3E = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 15, 59, 236, 944, 3776, 944, 236, 59, 15, 0, 0, 0},
};

const struct Glyph whiteFont3F = {
	NULL,
	0,
	6,
	{0, 0, 0, 1008, 3756, 15355, 15163, 3788, 944, 944, 192, 944, 944, 192, 0, 0},
};

const struct Glyph whiteFont40 = {
	NULL,
	0,
	6,
	{0, 0, 0, 1008, 3756, 15355, 15035, 15083, 15083, 15083, 15019, 15355, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont41 = {
	NULL,
	0,
	5,
	{0, 0, 0, 240, 940, 940, 3835, 3835, 3835, 3835, 3755, 3835, 3835, 780, 0, 0},
};

const struct Glyph whiteFont42 = {
	NULL,
	0,
	5,
	{0, 0, 0, 255, 939, 3835, 3835, 3835, 939, 3835, 3835, 3835, 939, 255, 0, 0},
};

const struct Glyph whiteFont43 = {
	NULL,
	0,
	5,
	{0, 0, 0, 240, 940, 3835, 3835, 827, 59, 827, 3835, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont44 = {
	NULL,
	0,
	5,
	{0, 0, 0, 255, 939, 3835, 3835, 3835, 3835, 3835, 3835, 3835, 939, 255, 0, 0},
};

const struct Glyph whiteFont45 = {
	NULL,
	0,
	5,
	{0, 0, 0, 1023, 3755, 1019, 59, 1019, 3755, 1019, 59, 1019, 3755, 1023, 0, 0},
};

const struct Glyph whiteFont46 = {
	NULL,
	0,
	5,
	{0, 0, 0, 1023, 3755, 1019, 59, 251, 939, 251, 59, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont47 = {
	NULL,
	0,
	5,
	{0, 0, 0, 240, 940, 3835, 3835, 827, 4091, 3771, 3835, 3835, 3756, 1008, 0, 0},
};

const struct Glyph whiteFont48 = {
	NULL,
	0,
	5,
	{0, 0, 0, 780, 3835, 3835, 3835, 3835, 3755, 3835, 3835, 3835, 3835, 780, 0, 0},
};

const struct Glyph whiteFont49 = {
	NULL,
	0,
	2,
	{0, 0, 0, 12, 59, 59, 59, 59, 59, 59, 59, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont4A = {
	NULL,
	0,
	5,
	{0, 0, 0, 768, 3776, 3776, 3776, 3776, 3788, 3835, 3835, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont4B = {
	NULL,
	0,
	5,
	{0, 0, 0, 780, 3835, 3835, 955, 955, 235, 955, 955, 3835, 3835, 780, 0, 0},
};

const struct Glyph whiteFont4C = {
	NULL,
	0,
	5,
	{0, 0, 0, 12, 59, 59, 59, 59, 59, 59, 59, 1019, 3755, 1023, 0, 0},
};

const struct Glyph whiteFont4D = {
	NULL,
	0,
	6,
	{0, 0, 0, 3084, 15163, 15163, 15163, 14811, 15083, 14955, 14747, 15291, 15355, 3084, 0, 0},
};

const struct Glyph whiteFont4E = {
	NULL,
	0,
	5,
	{0, 0, 0, 780, 3835, 3835, 3803, 3819, 3691, 3739, 3771, 3707, 3835, 780, 0, 0},
};

const struct Glyph whiteFont4F = {
	NULL,
	0,
	5,
	{0, 0, 0, 240, 940, 3835, 3835, 3835, 3835, 3835, 3835, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont50 = {
	NULL,
	0,
	5,
	{0, 0, 0, 255, 939, 3835, 3835, 3835, 939, 251, 59, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont51 = {
	NULL,
	0,
	6,
	{0, 0, 0, 240, 940, 3835, 3835, 3835, 3835, 3835, 3771, 3835, 15276, 15600, 0, 0},
};

const struct Glyph whiteFont52 = {
	NULL,
	0,
	5,
	{0, 0, 0, 255, 939, 3835, 3835, 3835, 939, 3995, 3515, 3707, 3835, 780, 0, 0},
};

const struct Glyph whiteFont53 = {
	NULL,
	0,
	5,
	{0, 0, 0, 240, 940, 3835, 3835, 1019, 940, 3836, 3835, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont54 = {
	NULL,
	0,
	6,
	{0, 0, 0, 4092, 15019, 4028, 944, 944, 944, 944, 944, 944, 944, 192, 0, 0},
};

const struct Glyph whiteFont55 = {
	NULL,
	0,
	5,
	{0, 0, 0, 780, 3835, 3835, 3835, 3835, 3835, 3835, 3835, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont56 = {
	NULL,
	0,
	6,
	{0, 0, 0, 3084, 15163, 15163, 15163, 14055, 3820, 3820, 3692, 944, 944, 192, 0, 0},
};

const struct Glyph whiteFont57 = {
	NULL,
	0,
	6,
	{0, 0, 0, 3084, 15355, 15291, 15291, 15291, 15291, 14747, 3692, 3820, 3820, 816, 0, 0},
};

const struct Glyph whiteFont58 = {
	NULL,
	0,
	6,
	{0, 0, 0, 15375, 15163, 15163, 3820, 3820, 944, 3820, 3820, 15163, 15163, 15375, 0, 0},
};

const struct Glyph whiteFont59 = {
	NULL,
	0,
	6,
	{0, 0, 0, 3084, 15163, 15163, 14055, 3692, 3484, 944, 944, 944, 944, 192, 0, 0},
};

const struct Glyph whiteFont5A = {
	NULL,
	0,
	5,
	{0, 0, 0, 1020, 3755, 3708, 944, 944, 924, 236, 236, 999, 3755, 1020, 0, 0},
};

const struct Glyph whiteFont5B = {
	NULL,
	0,
	3,
	{0, 0, 0, 63, 235, 59, 59, 59, 59, 59, 59, 59, 235, 63, 0, 0},
};

const struct Glyph whiteFont5C = {
	NULL,
	0,
	6,
	{0, 0, 0, 15375, 15163, 3820, 3484, 15019, 4028, 15019, 4028, 944, 944, 192, 0, 0},
};

const struct Glyph whiteFont5D = {
	NULL,
	0,
	3,
	{0, 0, 0, 252, 235, 236, 236, 236, 236, 236, 236, 236, 235, 252, 0, 0},
};

const struct Glyph whiteFont5E = {
	NULL,
	0,
	4,
	{0, 0, 0, 48, 236, 955, 204, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont5F = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 252, 939, 252, 0, 0},
};

const struct Glyph whiteFont60 = {
	NULL,
	0,
	2,
	{0, 0, 12, 59, 59, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont61 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 1008, 3756, 3835, 3835, 3835, 3707, 14763, 16380, 0, 0},
};

const struct Glyph whiteFont62 = {
	NULL,
	0,
	5,
	{0, 0, 0, 12, 59, 59, 59, 251, 939, 3835, 3835, 3835, 939, 255, 0, 0},
};

const struct Glyph whiteFont63 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 240, 940, 3835, 4091, 4091, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont64 = {
	NULL,
	0,
	5,
	{0, 0, 0, 768, 3776, 3776, 3776, 3824, 3756, 3835, 3835, 3835, 3756, 4080, 0, 0},
};

const struct Glyph whiteFont65 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 240, 940, 3835, 3755, 4091, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont66 = {
	NULL,
	0,
	4,
	{0, 0, 0, 1008, 940, 236, 236, 236, 939, 236, 236, 236, 236, 48, 0, 0},
};

const struct Glyph whiteFont67 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 4080, 3756, 3835, 3835, 3835, 3756, 3824, 3839, 3755, 1020},
};

const struct Glyph whiteFont68 = {
	NULL,
	0,
	5,
	{0, 0, 0, 12, 59, 59, 59, 251, 939, 3835, 3835, 3835, 3835, 780, 0, 0},
};

const struct Glyph whiteFont69 = {
	NULL,
	0,
	2,
	{0, 0, 0, 12, 59, 59, 12, 59, 59, 59, 59, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont6A = {
	NULL,
	0,
	4,
	{0, 0, 0, 192, 944, 944, 192, 944, 944, 944, 944, 944, 944, 956, 235, 60},
};

const struct Glyph whiteFont6B = {
	NULL,
	0,
	5,
	{0, 0, 0, 12, 59, 59, 3899, 3835, 955, 235, 955, 3835, 3835, 780, 0, 0},
};

const struct Glyph whiteFont6C = {
	NULL,
	0,
	2,
	{0, 0, 0, 12, 59, 59, 59, 59, 59, 59, 59, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont6D = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 4095, 13995, 15291, 15291, 15291, 15291, 15291, 15564, 0, 0},
};

const struct Glyph whiteFont6E = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 1023, 3499, 3835, 3835, 3835, 3835, 3835, 780, 0, 0},
};

const struct Glyph whiteFont6F = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 240, 940, 3835, 3835, 3835, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont70 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 255, 939, 3835, 3835, 3835, 939, 251, 59, 59, 12},
};

const struct Glyph whiteFont71 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 4080, 3756, 3835, 3835, 3835, 3756, 3824, 3776, 3776, 768},
};

const struct Glyph whiteFont72 = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 0, 12, 251, 939, 251, 59, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont73 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 240, 940, 3835, 1004, 956, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont74 = {
	NULL,
	0,
	4,
	{0, 0, 0, 0, 0, 48, 236, 236, 939, 236, 236, 236, 940, 240, 0, 0},
};

const struct Glyph whiteFont75 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 780, 3835, 3835, 3835, 3835, 3835, 940, 240, 0, 0},
};

const struct Glyph whiteFont76 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 3084, 15163, 15163, 14055, 3820, 3692, 944, 192, 0, 0},
};

const struct Glyph whiteFont77 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 3084, 15355, 15291, 15291, 14747, 3692, 3820, 816, 0, 0},
};

const struct Glyph whiteFont78 = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 15375, 15163, 3820, 944, 944, 3820, 15163, 15375, 0, 0},
};

const struct Glyph whiteFont79 = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 780, 3835, 3835, 3835, 3835, 3756, 3824, 3836, 939, 252},
};

const struct Glyph whiteFont7A = {
	NULL,
	0,
	5,
	{0, 0, 0, 0, 0, 0, 1020, 3755, 3708, 944, 876, 999, 3755, 4092, 0, 0},
};

const struct Glyph whiteFont7B = {
	NULL,
	0,
	4,
	{0, 0, 0, 192, 944, 236, 236, 236, 59, 236, 236, 236, 944, 192, 0, 0},
};

const struct Glyph whiteFont7C = {
	NULL,
	0,
	2,
	{0, 0, 0, 12, 59, 59, 59, 59, 59, 59, 59, 59, 59, 12, 0, 0},
};

const struct Glyph whiteFont7D = {
	NULL,
	0,
	4,
	{0, 0, 0, 12, 59, 236, 236, 236, 944, 236, 236, 236, 59, 12, 0, 0},
};

const struct Glyph whiteFont7E = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 48, 3308, 15291, 3788, 768, 0, 0, 0, 0, 0},
};

const struct Glyph whiteFont7F = {
	NULL,
	0,
	6,
	{0, 0, 0, 0, 0, 0, 0, 4092, 15019, 4092, 0, 0, 0, 0, 0, 0},
};

const struct Glyph * const whiteFonts[] = {
	&whiteFontList40,
	&whiteFontList41,
	&whiteFontList42,
	&whiteFontList43,
	&whiteFontList44,
	&whiteFontList45,
	&whiteFontList46,
	&whiteFontList47,
	&whiteFontList48,
	&whiteFontList49,
	&whiteFontList4A,
	&whiteFontList4B,
	&whiteFontList4C,
	&whiteFontList4D,
	&whiteFontList4E,
	&whiteFontList4F,
	&whiteFontList50,
	&whiteFontList51,
	&whiteFontList52,
	&whiteFontList53,
	&whiteFontList54,
	&whiteFontList55,
	&whiteFontList56,
	&whiteFontList57,
	&whiteFontList58,
	&whiteFontList59,
	&whiteFontList5A,
	&whiteFontList5B,
	&whiteFontList5C,
	&whiteFontList5D,
	&whiteFontList5E,
	&whiteFontList5F,
	&whiteFontList60,
	&whiteFontList61,
	&whiteFontList62,
	&whiteFontList63,
	&whiteFontList64,
	&whiteFontList65,
	&whiteFontList66,
	&whiteFontList67,
	&whiteFontList68,
	&whiteFontList69,
	&whiteFontList6A,
	&whiteFontList6B,
	&whiteFontList6C,
	&whiteFontList6D,
	&whiteFontList6E,
	&whiteFontList6F,
	&whiteFontList70,
	&whiteFontList71,
	&whiteFontList72,
	&whiteFontList73,
	&whiteFontList74,
	&whiteFontList75,
	&whiteFontList76,
	&whiteFontList77,
	&whiteFontList78,
	&whiteFontList79,
	&whiteFontList7A,
	&whiteFontList7B,
	&whiteFontList7C,
	&whiteFontList7D,
	&whiteFontList7E,
	NULL, // 7F
	&whiteFontList80,
	&whiteFontList81,
	&whiteFontList82,
	&whiteFontList83,
	&whiteFontList84,
	&whiteFontList85,
	&whiteFontList86,
	&whiteFontList87,
	&whiteFontList88,
	&whiteFontList89,
	&whiteFontList8A,
	&whiteFontList8B,
	&whiteFontList8C,
	&whiteFontList8D,
	&whiteFontList8E,
	&whiteFontList8F,
	&whiteFontList90,
	&whiteFontList91,
	&whiteFontList92,
	&whiteFontList93,
	&whiteFontList94,
	&whiteFontList95,
	&whiteFontList96,
	&whiteFontList97,
	&whiteFontList98,
	&whiteFontList99,
	&whiteFontList9A,
	&whiteFontList9B,
	&whiteFontList9C,
	&whiteFontList9D,
	&whiteFontList9E,
	&whiteFontList9F,
	&whiteFontListA0,
	&whiteFontListA1,
	&whiteFontListA2,
	&whiteFontListA3,
	&whiteFontListA4,
	&whiteFontListA5,
	&whiteFontListA6,
	&whiteFontListA7,
	&whiteFontListA8,
	&whiteFontListA9,
	&whiteFontListAA,
	&whiteFontListAB,
	&whiteFontListAC,
	&whiteFontListAD,
	&whiteFontListAE,
	&whiteFontListAF,
	&whiteFontListB0,
	&whiteFontListB1,
	&whiteFontListB2,
	&whiteFontListB3,
	&whiteFontListB4,
	&whiteFontListB5,
	&whiteFontListB6,
	&whiteFontListB7,
	&whiteFontListB8,
	&whiteFontListB9,
	&whiteFontListBA,
	&whiteFontListBB,
	&whiteFontListBC,
	&whiteFontListBD,
	&whiteFontListBE,
	&whiteFontListBF,
	&whiteFontListC0,
	&whiteFontListC1,
	&whiteFontListC2,
	&whiteFontListC3,
	&whiteFontListC4,
	&whiteFontListC5,
	&whiteFontListC6,
	&whiteFontListC7,
	&whiteFontListC8,
	&whiteFontListC9,
	&whiteFontListCA,
	&whiteFontListCB,
	&whiteFontListCC,
	&whiteFontListCD,
	&whiteFontListCE,
	&whiteFontListCF,
	&whiteFontListD0,
	&whiteFontListD1,
	&whiteFontListD2,
	&whiteFontListD3,
	&whiteFontListD4,
	&whiteFontListD5,
	&whiteFontListD6,
	&whiteFontListD7,
	&whiteFontListD8,
	&whiteFontListD9,
	&whiteFontListDA,
	&whiteFontListDB,
	&whiteFontListDC,
	&whiteFontListDD,
	&whiteFontListDE,
	&whiteFontListDF,
	&whiteFontListE0,
	&whiteFontListE1,
	&whiteFontListE2,
	&whiteFontListE3,
	&whiteFontListE4,
	&whiteFontListE5,
	&whiteFontListE6,
	&whiteFontListE7,
	&whiteFontListE8,
	&whiteFontListE9,
	&whiteFontListEA,
	&whiteFontListEB,
	&whiteFontListEC,
	&whiteFontListED,
	&whiteFontListEE,
	&whiteFontListEF,
	&whiteFontListF0,
	&whiteFontListF1,
	&whiteFontListF2,
	&whiteFontListF3,
	&whiteFontListF4,
	&whiteFontListF5,
	&whiteFontListF6,
	&whiteFontListF7,
	&whiteFontListF8,
	&whiteFontListF9,
	&whiteFontListFA,
	&whiteFontListFB,
	&whiteFontListFC,
	&whiteFontGbFDF7,
	&whiteFontGbFEF7,
	NULL, // FF

	NULL, // 0
	NULL, // 1
	NULL, // 2
	NULL, // 3
	NULL, // 4
	NULL, // 5
	NULL, // 6
	NULL, // 7
	NULL, // 8
	NULL, // 9
	NULL, // A
	NULL, // B
	NULL, // C
	NULL, // D
	NULL, // E
	NULL, // F
	NULL, // 10
	NULL, // 11
	NULL, // 12
	NULL, // 13
	NULL, // 14
	NULL, // 15
	NULL, // 16
	NULL, // 17
	NULL, // 18
	NULL, // 19
	NULL, // 1A
	NULL, // 1B
	NULL, // 1C
	NULL, // 1D
	NULL, // 1E
	&whiteFont1F,
	&whiteFont20,
	&whiteFont21,
	&whiteFont22,
	&whiteFont23,
	&whiteFont24,
	&whiteFont25,
	&whiteFont26,
	&whiteFont27,
	&whiteFont28,
	&whiteFont29,
	&whiteFont2A,
	&whiteFont2B,
	&whiteFont2C,
	&whiteFont2D,
	&whiteFont2E,
	&whiteFont2F,
	&whiteFont30,
	&whiteFont31,
	&whiteFont32,
	&whiteFont33,
	&whiteFont34,
	&whiteFont35,
	&whiteFont36,
	&whiteFont37,
	&whiteFont38,
	&whiteFont39,
	&whiteFont3A,
	&whiteFont3B,
	&whiteFont3C,
	&whiteFont3D,
	&whiteFont3E,
	&whiteFont3F,
	&whiteFont40,
	&whiteFont41,
	&whiteFont42,
	&whiteFont43,
	&whiteFont44,
	&whiteFont45,
	&whiteFont46,
	&whiteFont47,
	&whiteFont48,
	&whiteFont49,
	&whiteFont4A,
	&whiteFont4B,
	&whiteFont4C,
	&whiteFont4D,
	&whiteFont4E,
	&whiteFont4F,
	&whiteFont50,
	&whiteFont51,
	&whiteFont52,
	&whiteFont53,
	&whiteFont54,
	&whiteFont55,
	&whiteFont56,
	&whiteFont57,
	&whiteFont58,
	&whiteFont59,
	&whiteFont5A,
	&whiteFont5B,
	&whiteFont5C,
	&whiteFont5D,
	&whiteFont5E,
	&whiteFont5F,
	&whiteFont60,
	&whiteFont61,
	&whiteFont62,
	&whiteFont63,
	&whiteFont64,
	&whiteFont65,
	&whiteFont66,
	&whiteFont67,
	&whiteFont68,
	&whiteFont69,
	&whiteFont6A,
	&whiteFont6B,
	&whiteFont6C,
	&whiteFont6D,
	&whiteFont6E,
	&whiteFont6F,
	&whiteFont70,
	&whiteFont71,
	&whiteFont72,
	&whiteFont73,
	&whiteFont74,
	&whiteFont75,
	&whiteFont76,
	&whiteFont77,
	&whiteFont78,
	&whiteFont79,
	&whiteFont7A,
	&whiteFont7B,
	&whiteFont7C,
	&whiteFont7D,
	&whiteFont7E,
	&whiteFont7F,
	NULL, // 0
	NULL, // 1
	NULL, // 2
	NULL, // 3
	NULL, // 4
	NULL, // 5
	NULL, // 6
	NULL, // 7
	NULL, // 8
	NULL, // 9
	NULL, // A
	NULL, // B
	NULL, // C
	NULL, // D
	NULL, // E
	NULL, // F
	NULL, // 10
	NULL, // 11
	NULL, // 12
	NULL, // 13
	NULL, // 14
	NULL, // 15
	NULL, // 16
	NULL, // 17
	NULL, // 18
	NULL, // 19
	NULL, // 1A
	NULL, // 1B
	NULL, // 1C
	NULL, // 1D
	NULL, // 1E
	&whiteFont1F,
	&whiteFont20,
	&whiteFont21,
	&whiteFont22,
	&whiteFont23,
	&whiteFont24,
	&whiteFont25,
	&whiteFont26,
	&whiteFont27,
	&whiteFont28,
	&whiteFont29,
	&whiteFont2A,
	&whiteFont2B,
	&whiteFont2C,
	&whiteFont2D,
	&whiteFont2E,
	&whiteFont2F,
	&whiteFont30,
	&whiteFont31,
	&whiteFont32,
	&whiteFont33,
	&whiteFont34,
	&whiteFont35,
	&whiteFont36,
	&whiteFont37,
	&whiteFont38,
	&whiteFont39,
	&whiteFont3A,
	&whiteFont3B,
	&whiteFont3C,
	&whiteFont3D,
	&whiteFont3E,
	&whiteFont3F,
	&whiteFont40,
	&whiteFont41,
	&whiteFont42,
	&whiteFont43,
	&whiteFont44,
	&whiteFont45,
	&whiteFont46,
	&whiteFont47,
	&whiteFont48,
	&whiteFont49,
	&whiteFont4A,
	&whiteFont4B,
	&whiteFont4C,
	&whiteFont4D,
	&whiteFont4E,
	&whiteFont4F,
	&whiteFont50,
	&whiteFont51,
	&whiteFont52,
	&whiteFont53,
	&whiteFont54,
	&whiteFont55,
	&whiteFont56,
	&whiteFont57,
	&whiteFont58,
	&whiteFont59,
	&whiteFont5A,
	&whiteFont5B,
	&whiteFont5C,
	&whiteFont5D,
	&whiteFont5E,
	&whiteFont5F,
	&whiteFont60,
	&whiteFont61,
	&whiteFont62,
	&whiteFont63,
	&whiteFont64,
	&whiteFont65,
	&whiteFont66,
	&whiteFont67,
	&whiteFont68,
	&whiteFont69,
	&whiteFont6A,
	&whiteFont6B,
	&whiteFont6C,
	&whiteFont6D,
	&whiteFont6E,
	&whiteFont6F,
	&whiteFont70,
	&whiteFont71,
	&whiteFont72,
	&whiteFont73,
	&whiteFont74,
	&whiteFont75,
	&whiteFont76,
	&whiteFont77,
	&whiteFont78,
	&whiteFont79,
	&whiteFont7A,
	&whiteFont7B,
	&whiteFont7C,
	&whiteFont7D,
	&whiteFont7E,
	&whiteFont7F,
};

const struct Glyph * const * const pWhiteFonts = &whiteFonts[0];
