version: 2.1
executors:
  my-executor:
    docker:
      - image: devkitpro/devkitarm
jobs:
  build:
    executor: my-executor
    working_directory: ~/FEHRG
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run:
        name: Dependancy
        command: |
          echo "deb http://ftp.de.debian.org/debian buster main" >> /etc/apt/sources.list
          apt-get update && apt-get -y install sox
    - run:
        name: Baserom
        command: |
          head -c 16MB /dev/urandom > baserom.gba
    - run:
          name: Make
          command: |
            make
workflows:
  nightly:
    jobs:
    - build
