version: 2.1
executors:
  my-executor:
    docker:
      - image: devkitpro/devkitarm
jobs:
  build:
    executor: my-executor
    working_directory: ~/FEHRG
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run:
        name: Dependancy
        command: |
          tool/install_sox_from_source.sh
    - run:
        name: Baserom
        command: |
          head -c 16MB /dev/urandom > baserom.gba
    - run:
          name: Make
          command: |
            make
workflows:
  nightly:
    jobs:
    - build
