version: 2.1
executors:
  my-executor:
    docker:
      - image: devkitpro/devkitarm
jobs:
  build:
    executor: my-executor
    working_directory: ~/FEHRG
    steps:
    - checkout
    - run:
        name: Baserom
        command: |
          head -c 16MB /dev/urandom > baserom.gba
    - run:
        name: Dependancy
        command: |
          curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py && python3 -m pip install numpy
    - run:
          name: Make
          command: |
            make
workflows:
  nightly:
    jobs:
    - build
