#!/usr/bin/env python3

import struct

white_fonts = []
black_fonts = []

def next_font(fp, p):
    fp.seek(p - 0x8000000)
    return struct.unpack("<I", fp.read(4))[0]

with open("../../baserom.gba", mode='rb') as f_rom, open("../../linkerscript/font.lds", mode="w") as f_lds:
    f_lds.write("/* Generated by tool/font/make_linker_script.py. */\n\n")
    for i in range(0xc0):
        p = 0x8bc1fec + 4 * i
        while p != 0:
            p0 = p
            p = next_font(f_rom, p)
        f_lds.write(". = 0x{:x};\n.rodata.whiteFonts{:X} : {{*(.rodata.whiteFonts{:X})}}\n".format(p0, 0x40 + i, 0x40 + i))
    f_lds.write("\n")
    for i in range(0xc0):
        p = 0x8bdc1e0 + 4 * i
        while p != 0:
            p0 = p
            p = next_font(f_rom, p)
        f_lds.write(". = 0x{:x};\n.rodata.blackFonts{:X} : {{*(.rodata.blackFonts{:X})}}\n".format(p0, 0x40 + i, 0x40 + i))
