const char *musicNames[] = {
    "Opening: History Unveiled",
    "Fire Emblem Theme",
    "A Hint of Things to Come",
    "Road of Trials",
    "Destiny Enlaced by Fear",
    "Winds across the Plains",
    "Precious Things",
    "Companions",
    "Friendship and Adventure",
    "Distant Travels",
    "Inescapable Fate",
    "Dragon's Gate II",
    "Winning Road",
    "Binding Ties",
    "Scars of the Scouring",
    "Raise Your Spirits",
    "Shadow Approaches",
    "Enemies Appear",
    "The Messenger",
    "Darkness Comes",
    "Dragon's Gate I",
    "Nabata's Wandering Messenger",
    "Legendary Inheritance",
    "Raid!",
    "Messenger from the Darkness",
    "Strike",
    "Safeguard",
    "Victory Now!",
    "Rise to the Challenge",
    "Softly with Grace",
    "Everything into the Dark",
    "Campaign of Fire",
    "Blessing of the 8 Generals I",
    "Healing",
    "Curing",
    "Receive the Blessings of Water",
    "Ride the Wind",
    "To the Heights",
    "An Unexpected Caller",
    "When the Rush Comes",
    "Land of Swirling Sands",
    "Ships and Homes",
    "Silent Ground",
    "The Inn",
    "Going My Way",
    "Together, We Ride!",
    "A Knight's Oath",
    "Happiness Abounds",
    "Merlinus",
    "Final Farewell",
    "Requiem",
    "Recollection of a Petal",
    "The Cogs of Fate",
    "The Eight Generals",
    "The Archsage Athos",
    "Distant Utopia",
    "What Comes from Darkness",
    "Black Fang",
    "Calamity Bringer: Nergal's Theme",
    "Nergal's Wrath",
    "Stratagem",
    "The Kingdom of Bern",
    "Bern - A Mother's Wish",
    "Shocking Truth I",
    "Shocking Truth II",
    "Triumph",
    "Into the Shadow of Triumph",
    "Main Theme Arrangement",
    "Blessing of the 8 Generals II",
    "Girl of the Plains: Lyn's Theme",
    "Lyn's Desire",
    "Light to Tomorrow",
    "One Heart: Eliwood's Theme",
    "Eyes of Sorrow",
    "Unshakable Faith",
    "Loyalty: Hector's Theme",
    "The Grieving Heart",
    "Reminiscence",
    "Shattered Life",
    "Anguish",
    "Respite in Battle",
    "Prepare to Charge",
    "Armory",
    "Shop",
    "Fortune-Telling",
    "Arena Entrance",
    "Arena Battle",
    "Arena Victory",
    "Arena Tactics",
    "Within Sadness",
    "Game Over",
    "Legend of Athos",
    "Results",
    "Treasured Hope",
    "Beneath a New Light",
    "The Path to Greatness",
    "In the Name of Bern",
    "Avoided Fate",
    "Legend of the Dragon God",
    "Royal Palace of Silezha",
    "Prologue to World Map",
    "Long Silence (MIDI Data)",
    "Lyn's Organ",
    "The Inn",
    "Fire Emblem Theme",
    "Fire Emblem Theme Loop",
    "Final Battle (Sans Intro)",
};
