#pragma once

// From: Event Assembler/EA Standard Library/FE7 Definitions.txt

#define EliwoodLord 0x01
#define LynLord 0x02
#define HectorLord 0x03
#define KnightLord 0x07
#define BladeLord 0x08
#define GreatLord 0x09
#define Mercenary 0x0A
#define Mercenary_F 0x0B
#define Hero 0x0C
#define Hero_F 0x0D
#define Myrmidon 0x0E
#define Myrmidon_F 0x0F
#define Swordmaster 0x10
#define Swordmaster_F 0x11
#define Fighter 0x12
#define Warrior 0x13
#define Knight 0x14
#define Knight_F 0x15
#define General 0x16
#define General_F 0x17
#define Archer 0x18
#define Archer_F 0x19
#define Sniper 0x1A
#define Sniper_F 0x1B
#define Monk 0x1C
#define Cleric 0x1D
#define Bishop 0x1E
#define Bishop_F 0x1F
#define Mage 0x20
#define Mage_F 0x21
#define Sage 0x22
#define Sage_F 0x23
#define Shaman 0x24
#define Shaman_F 0x25
#define Druid 0x26
#define Druid_F 0x27
#define Cavalier 0x28
#define Cavalier_F 0x29
#define Paladin 0x2A
#define Paladin_F 0x2B
#define Troubadour 0x2C
#define Valkyrie 0x2D
#define Nomad 0x2E
#define Nomad_F 0x2F
#define NomadTrooper 0x30
#define NomadTrooper_F 0x31
#define PegasusKnight 0x32
#define FalcoKnight 0x33
#define WyvernKnight 0x34
#define WyvernKnight_F 0x35
#define WyvernLord 0x36
#define WyvernLord_F 0x37
#define Soldier 0x38
#define Brigand 0x39
#define Pirate 0x3A
#define Berserker 0x3B
#define Thief 0x3C
#define Thief_F 0x3D
#define Assassin 0x3E
#define Civilian 0x3F
#define Dancer 0x40
#define Bard 0x41
#define Archsage 0x42
#define MagicSeal 0x43
#define Transporter 0x44
#define DarkDruid 0x45
#define FireDragon 0x46
#define Civilian_2 0x47
#define Civilian_2_F 0x48
#define Child 0x49
#define Brammimond 0x4A
#define Peer 0x4B
#define Peer_F 0x4C
#define Prince 0x4D
#define Queen 0x4E
#define HungLeila 0x4F
#define Corsair 0x50
#define Prince_Tactician 0x51
#define FallenPrince 0x52
#define PrinceFacingUpward 0x53
#define FallenNinian 0x54
#define FallenIceDragon 0x55
#define FallenWarrior 0x56
#define Child_2 0x57
#define Child_2_F 0x58
#define TransporterHorse 0x59
#define UberSage 0x5A
#define ArcherInBallista 0x5B
#define ArcherInIronBallista 0x5C
#define ArcherInKillerBallista 0x5D
#define EmptyBallista 0x5E
#define EmptyIronBallista 0x5F
#define EmptyKillerBallista 0x60

// From: http://theemblems.fc2web.com/gba_codes/FE-rekka_class.html

#define ロードエリウッド 1
#define ロードリン 2
#define ロードヘクトル 3
#define リキア騎士 4
#define リキア剣士 5
#define リキア重騎士 6
#define ロードナイト 7
#define ブレイドロード 8
#define グレートロード 9
#define 傭兵男 10
#define 傭兵女 11
#define 勇者男 12
#define 勇者女 13
#define 剣士男 14
#define 剣士女 15
#define ソードマスター男 16
#define ソードマスター女 17
#define 戦士 18
#define ウォーリア 19
#define アーマーナイト男 20
#define アーマーナイト女 21
#define ジェネラル男 22
#define ジェネラル女 23
#define アーチャー男 24
#define アーチャー女 25
#define スナイパー男 26
#define スナイパー女 27
#define 修道士 28
#define シスター 29
#define 司祭男 30
#define 司祭女 31
#define 魔道士男 32
#define 魔道士女 33
#define 賢者男 34
#define 賢者女 35
#define シャーマン男 36
#define シャーマン女 37
#define ドルイド男 38
#define ドルイド女 39
#define ソシアルナイト男 40
#define ソシアルナイト女 41
#define パラディン男 42
#define パラディン女 43
#define トルバドール 44
#define ヴァルキリア 45
#define 遊牧民男 46
#define 遊牧民女 47
#define 遊牧騎兵男 48
#define 遊牧騎兵女 49
#define ペガサスナイト 50
#define ファルコンナイト 51
#define ドラゴンナイト男 52
#define ドラゴンナイト女 53
#define ドラゴンマスター男 54
#define ドラゴンマスター女 55
#define ソルジャー 56
#define 山賊 57
#define 海賊 58
#define 狂戦士 59
#define 盗賊男 60
#define 盗賊女 61
#define アサシン 62
#define 市民倒れ 63
#define 踊り子 64
#define バード 65
#define 大賢者 66
#define 魔封じの者 67
#define 輸送隊テント 68
#define 災いを招く者 69
#define 古の火竜 70
#define 市民男 71
#define 市民女 72
#define ニルス倒れ 73
#define ブラミモンド 74
#define 貴族男 75
#define 貴族女 76
#define ベルン王国王子 77
#define 王女 78
#define アサシン女レイラ 79
#define 湖賊 80
#define ベルン王国王子前部 81
#define ベルン王国王子倒れ 82
#define ベルン王国王子後部 83
#define ニニアン倒れ 84
#define 氷竜倒れ 85
#define ウォーリア倒れ 86
#define 子供男 87
#define 子供女 88
#define 輸送隊馬車 89
#define 賢者女リムステラ 90

// From: http://bbs.fireemblem.net/read.php?tid=125890

#define 领主艾利乌德 0x01
#define 领主琳 0x02
#define 领主赫克托尔 0x03
#define 利西亚骑士 0x04
#define 利西亚剑士 0x05
#define 利西亚重骑士 0x06
#define 领主骑士 0x07
#define 利刃领主 0x08
#define 重装领主 0x09
#define 佣兵男 0x0A
#define 佣兵女 0x0B
//#define 勇者男 0x0C
//#define 勇者女 0x0D
#define 剑士男 0x0E
#define 剑士女 0x0F
#define 剑圣男 0x10
#define 剑圣女 0x11
#define 战士 0x12
//#define 勇士 0x13
#define 重甲骑士男 0x14
#define 重甲骑士女 0x15
#define 将军男 0x16
#define 将军女 0x17
#define 弓箭手男 0x18
#define 弓箭手女 0x19
#define 狙击手男 0x1A
#define 狙击手女 0x1B
//#define 修道士 0x1C
#define 修女 0x1D
//#define 司祭男 0x1E
//#define 司祭女 0x1F
#define 魔法师男 0x20
#define 魔法师女 0x21
#define 贤者男 0x22
#define 贤者女 0x23
#define 巫师男 0x24
#define 巫师女 0x25
#define 德鲁伊男 0x26
#define 德鲁伊女 0x27
#define 轻骑士男 0x28
#define 轻骑士女 0x29
#define 圣骑士男 0x2A
#define 圣骑士女 0x2B
#define 神官骑士 0x2C
#define 女武神 0x2D
#define 游牧民男 0x2E
#define 游牧民女 0x2F
#define 游牧骑兵男 0x30
#define 游牧骑兵女 0x31
#define 天马骑士 0x32
#define 隼骑士 0x33
#define 龙骑士男 0x34
#define 龙骑士女 0x35
#define 龙骑统帅男 0x36
#define 龙骑统帅女 0x37
#define 士兵 0x38
#define 山贼 0x39
#define 海盗 0x3A
#define 狂战士 0x3B
#define 盗贼男 0x3C
#define 盗贼女 0x3D
#define 刺客 0x3E
#define 市民倒地 0x3F
#define 舞者 0x40
#define 吟游诗人 0x41
#define 大贤者 0x42
#define 封魔者 0x43
#define 运输队帐篷 0x44
#define 灾祸招致者 0x45
#define 太古火龙 0x46
//#define 市民男 0x47
//#define 市民女 0x48
#define 尼尔斯倒地 0x49
#define 布拉米蒙德 0x4A
#define 贵族男 0x4B
#define 贵族女 0x4C
#define 伯尔尼王子 0x4D
#define 公主 0x4E
#define 刺客女蕾拉 0x4F
#define 湖盗 0x50
#define 王子军师前面 0x51
#define 王子军师倒地 0x52
#define 王子军师背面 0x53
#define 妮妮安倒地 0x54
#define 冰龙倒地 0x55
#define 勇士倒地 0x56
#define 孩子男 0x57
#define 孩子女 0x58
#define 运输队马车 0x59
#define 贤者魔将 0x5A
#define 弩车手 0x5B
#define 长弩车手 0x5C
#define 必杀弩车手 0x5D
#define 空弩车 0x5E
#define 空长弩车 0x5F
#define 空必杀弩车 0x60

// From: Event Assembler/EA Standard Library/FE6 Definitions.txt

#define RoyLord 0x61
#define RoyMasterLord 0x62
#define MountainThief Brigand
#define Mamkute 0x63
#define Mamkute_F 0x64
#define DivineDragon 0x65
#define MagicDragon 0x66
#define King 0x67

// From: http://gbacode.web.fc2.com/gba-fire_emblem.html

#define ロードロイ RoyLord
#define マスターロードロイ RoyMasterLord
#define マムクート男 Mamkute
#define マムクート女 Mamkute_F
#define 神竜 DivineDragon
#define 魔竜 MagicDragon
#define 国王 King

#define 领主罗伊 RoyLord
#define 大领主罗伊 RoyMasterLord
#define 龙人男 Mamkute
#define 龙人女 Mamkute_F
#define 神龙 DivineDragon
#define 魔龙 MagicDragon

// From: Event Assembler/Event Assembler/EA Standard Library/FE8 Definitions.txt

#define EphraimLord 0x68
#define EirikaLord 0x69
#define EphraimMasterLord 0x6A
#define EirikaMasterLord 0x6B
#define Manakete 0x6C
#define WyvernRider 0x6D
#define WyvernRider_F 0x6E
#define Ranger 0x6F
#define Ranger_F 0x70
#define Summoner 0x71
#define Summoner_F 0x72
#define Rogue 0x73
#define GreatKnight 0x74
#define GreatKnight_F 0x75
#define Recruit 0x76
#define Journeyman 0x77
#define Pupil 0x78
#define Necromancer 0x79
#define Mauthedoog 0x7A

// From: http://gbacode.web.fc2.com/gba-fire_emblem_3.html

#define ロードエフラム EphraimLord
#define ロードエイリーク EirikaLord
#define マスターロードエフラム EphraimMasterLord
#define マスターロードエイリーク EirikaMasterLord
#define マムクートミルラ Manakete
#define ワイバーンナイト男 WyvernRider
#define ワイバーンナイト女 WyvernRider_F
#define フォレストナイト男 Ranger
#define フォレストナイト女 Ranger_F
#define サマナー男 Summoner
#define サマナー女 Summoner_F
#define ローグ Rogue
#define グレートナイト男 GreatKnight
#define グレートナイト女 GreatKnight_F
#define 新人兵士 Recruit
#define かけだし戦士 Journeyman
#define 魔道士見習い Pupil
#define ネクロマンサー Necromancer
#define モーサドゥーグ Mauthedoog

// from: http://bbs.fireemblem.net/read.php?tid=125890&fpage=1

#define 领主伊弗列姆 EphraimLord
#define 领主艾瑞珂 EirikaLord
#define 大领主伊弗列姆 EphraimMasterLord
#define 大领主艾瑞珂 EirikaMasterLord
#define 龙人梅尔 Manakete
#define 翼龙骑士男 WyvernRider
#define 翼龙骑士女 WyvernRider_F
#define 丛林骑士男 Ranger
#define 丛林骑士女 Ranger_F
#define 召唤士男 Summoner
#define 召唤士女 Summoner_F
#define 侠盗 Rogue
#define 重骑士男 GreatKnight
#define 重骑士女 GreatKnight_F
#define 新人士兵 Recruit
#define 年轻战士 Journeyman
#define 见习魔法师 Pupil
#define 亡灵巫师 Necromancer
#define 魔刹犬 Mauthedoog

// Custom

#define AnnaLord 0x7B
#define AnnaMasterLord 0x7C
#define Halberdier 0x7D
#define Halberdier_F 0x7E
#define Vanguard 0x7F
#define RangerIke FallenWarrior
#define IkeLord RangerIke
#define IkeMasterLord Vanguard

#define ロードアンナ AnnaLord
#define マスターロードアンナ AnnaMasterLord
#define ハルバーディア男 Halberdier
#define ハルバーディア女 Halberdier_F
#define 槍闘士男 Halberdier
#define 槍闘士女 Halberdier_F
#define ロードアイク IkeLord
#define マスターロードアイク IkeMasterLord

#define 领主安娜 AnnaLord
#define 大领主安娜 AnnaMasterLord
#define 枪术师男 Halberdier
#define 枪术师女 Halberdier_F
#define 领主艾克 IkeLord
#define 大领主艾克 IkeMasterLord

// Character's default class

#define 歩行_剣 剑士男
#define 歩行_槍 士兵
#define 歩行_斧 战士
#define 歩行_弓 弓箭手男
#define 歩行_赤弓 歩行_弓
#define 歩行_青弓 歩行_弓
#define 歩行_緑弓 歩行_弓
#define 歩行_暗 盗贼男
#define 歩行_赤暗 歩行_暗
#define 歩行_青暗 歩行_暗
#define 歩行_緑暗 歩行_暗
#define 歩行_赤魔 巫师男
#define 歩行_青魔 修道士
#define 歩行_緑魔 魔法师男
#define 歩行_無魔 魔法师男
#define 歩行_杖 修女
#define 歩行_無竜 龙人女
#define 歩行_赤竜 歩行_無竜
#define 歩行_青竜 歩行_無竜
#define 歩行_緑竜 歩行_無竜
#define 歩行_無獣 魔刹犬
#define 歩行_赤獣 歩行_無獣
#define 歩行_青獣 歩行_無獣
#define 歩行_緑獣 歩行_無獣

#define 重装_剣 重甲骑士男
#define 重装_槍 重甲骑士男
#define 重装_斧 重甲骑士男
#define 重装_弓 重甲骑士男
#define 重装_赤弓 重装_弓
#define 重装_青弓 重装_弓
#define 重装_緑弓 重装_弓
#define 重装_暗 重甲骑士男
#define 重装_赤暗 重装_暗
#define 重装_青暗 重装_暗
#define 重装_緑暗 重装_暗
#define 重装_赤魔 重甲骑士男
#define 重装_青魔 重甲骑士男
#define 重装_緑魔 重甲骑士男
#define 重装_無魔 重甲骑士男
#define 重装_杖 重甲骑士男
#define 重装_無竜 龙人女
#define 重装_赤竜 重装_無竜
#define 重装_青竜 重装_無竜
#define 重装_緑竜 重装_無竜
#define 重装_無獣 魔刹犬
#define 重装_赤獣 重装_無獣
#define 重装_青獣 重装_無獣
#define 重装_緑獣 重装_無獣

#define 騎馬_剣 轻骑士男
#define 騎馬_槍 轻骑士男
#define 騎馬_斧 轻骑士男
#define 騎馬_弓 游牧民男
#define 騎馬_赤弓 騎馬_弓
#define 騎馬_青弓 騎馬_弓
#define 騎馬_緑弓 騎馬_弓
#define 騎馬_暗 游牧民男
#define 騎馬_赤暗 騎馬_暗
#define 騎馬_青暗 騎馬_暗
#define 騎馬_緑暗 騎馬_暗
#define 騎馬_赤魔 神官骑士
#define 騎馬_青魔 神官骑士
#define 騎馬_緑魔 神官骑士
#define 騎馬_無魔 神官骑士
#define 騎馬_杖 神官骑士
#define 騎馬_無竜 龙人女
#define 騎馬_赤竜 騎馬_無竜
#define 騎馬_青竜 騎馬_無竜
#define 騎馬_緑竜 騎馬_無竜
#define 騎馬_無獣 魔刹犬
#define 騎馬_赤獣 騎馬_無獣
#define 騎馬_青獣 騎馬_無獣
#define 騎馬_緑獣 騎馬_無獣

#define 飛行_剣 龙骑士男
#define 飛行_槍 龙骑士男
#define 飛行_斧 龙骑士男
#define 飛行_弓 龙骑士男
#define 飛行_赤弓 飛行_弓
#define 飛行_青弓 飛行_弓
#define 飛行_緑弓 飛行_弓
#define 飛行_暗 龙骑士男
#define 飛行_赤暗 飛行_暗
#define 飛行_青暗 飛行_暗
#define 飛行_緑暗 飛行_暗
#define 飛行_赤魔 天马骑士
#define 飛行_青魔 天马骑士
#define 飛行_緑魔 天马骑士
#define 飛行_無魔 天马骑士
#define 飛行_杖 天马骑士
#define 飛行_無竜 龙人梅尔
#define 飛行_赤竜 飛行_無竜
#define 飛行_青竜 飛行_無竜
#define 飛行_緑竜 飛行_無竜
#define 飛行_無獣 魔刹犬
#define 飛行_赤獣 飛行_無獣
#define 飛行_青獣 飛行_無獣
#define 飛行_緑獣 飛行_無獣

