#pragma once

#define BYTES_PER_WORD 4
#define BYTES_PER_HWORD 2
#define BYTES_PER_COLOR BYTES_PER_HWORD

#define FRAMES_PER_SECOND 60
#define SECONDS_PER_MINUTE 60

#define COLORS_PER_PALETTE_SLOT 16
#define TILES_PER_LINE_16_COLOR 32
#define TILES_PER_LINE_256_COLOR TILES_PER_LINE_16_COLOR / 2
#define TILES_PER_BLOCK_16_COLOR 512
#define TILES_PER_BLOCK_256_COLOR TILES_PER_BLOCK_16_COLOR / 2
#define TILE_WIDTH 8
#define TILE_HEIGHT 8
#define MAP_TILE_WIDTH 16
#define MAP_TILE_HEIGHT 16

#define MAX_GOLD_AMOUNT 999999

enum AnimationSide {
    LEFT_SIDE,
    RIGHT_SIDE
};
