#pragma once

enum TEXT_ID {
    TID_START = 0x1236,
    TID_OPTION_LANGUAGE,
    TID_OPTION_LANGUAGE_JP,
    TID_OPTION_LANGUAGE_JP_HELP,
    TID_OPTION_LANGUAGE_CN,
    TID_OPTION_LANGUAGE_CN_HELP,
    TID_OPTION_LANGUAGE_EN,
    TID_OPTION_LANGUAGE_EN_HELP,
    TID_OPTION_LANGUAGE_EN_NARROW,
    TID_OPTION_LANGUAGE_EN_NARROW_HELP,
};
