#pragma once

struct Voice {
    const struct Sound * attack;
    const struct Sound * map;
    const struct Sound * damage;
    const struct Sound * status;
};

extern const struct Voice voices[];

void playVoice(const struct Sound *voice);

#define DEFINE_VOICE(roman) {&VOICE_##roman##_ATTACK_1, &VOICE_##roman##_MAP_1, &VOICE_##roman##_DAMAGE_1, &VOICE_##roman##_STATUS_1},

#define VOICE_ALFONS_PAIR01_DAMAGE_1 VOICE_ALFONS_PAIR01_DAMAGE_1A
#define VOICE_ARUM_PAIR01_DAMAGE_1 VOICE_ARUM_PAIR01_DAMAGE_1A
#define VOICE_BELETH_PAIR01_DAMAGE_1 VOICE_BELETH_PAIR01_DAMAGE_1A
#define VOICE_HECTOR_PAIR01_DAMAGE_1 VOICE_HECTOR_PAIR01_DAMAGE_1A
#define VOICE_IDENN_PAIR01_DAMAGE_1 VOICE_IDENN_PAIR01_DAMAGE_1A
#define VOICE_MARTH_PAIR01_DAMAGE_1 VOICE_MARTH_PAIR01_DAMAGE_1A
#define VOICE_MICAIAH_PAIR01_DAMAGE_1 VOICE_MICAIAH_PAIR01_DAMAGE_1A
#define VOICE_PAORA_PAIR01_DAMAGE_1 VOICE_PAORA_PAIR01_DAMAGE_1A
#define VOICE_SIGLUD_PAIR01_DAMAGE_1 VOICE_SIGLUD_PAIR01_DAMAGE_1A
#define VOICE_VERONICA_PAIR01_DAMAGE_1 VOICE_VERONICA_PAIR01_DAMAGE_1A
#define VOICE_WAYU_PAIR01_DAMAGE_1 VOICE_WAYU_PAIR01_DAMAGE_1A

